import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LocalizationProvider extends ChangeNotifier {
  Locale _locale = const Locale('en', 'US');
  
  LocalizationProvider() {
    _loadLocale();
  }

  Locale get locale => _locale;

  Future<void> _loadLocale() async {
    final prefs = await SharedPreferences.getInstance();
    final languageCode = prefs.getString('language_code');
    if (languageCode != null) {
      if (languageCode == 'en') {
        _locale = const Locale('en', 'US');
      } else {
        _locale = Locale(languageCode);
      }
      notifyListeners();
    }
  }

  Future<void> setLocale(Locale locale) async {
    if (!['en', 'hi', 'te', 'ml', 'kn', 'ta'].contains(locale.languageCode)) return;
    _locale = locale;
    notifyListeners();
    
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString('language_code', locale.languageCode);
  }

  // Simple key-value map for strings
  final Map<String, Map<String, String>> _localizedStrings = {
    'en': {
      'login_title': 'Drivara Driver',
      'login_subtitle': 'Enter your number to login',
      'phone_hint': 'Mobile Number',
      'get_started': 'Get Started',
      'verify_otp': 'Verify & Login',
      'otp_sent_to': 'Sent to',
      'enter_otp': 'Enter OTP',
      'active_job': 'Active Job',
      'no_active_job': 'No Active Trips',
      'logout': 'Logout',
      'start_trip': 'Start Trip',
      'end_trip': 'End Trip',
      'view_route': 'View Route Plan',
      'add_expense': 'Add Expense',
      'welcome': 'Welcome',
      'you_are_all_set': 'You are all set!',
      'permissions_title': 'Permissions',
      'permissions_subtitle': 'To verify your identity and track your trips, Drivara needs access to the following:',
      'perm_location_title': 'Location Access',
      'perm_location_desc': 'Required to track your trips and calculate mileage.',
      'perm_contacts_title': 'Contacts',
      'perm_contacts_desc': 'To sync your network and verify references.',
      'perm_sms_title': 'SMS Access',
      'perm_sms_desc': 'For account verification and transaction alerts.',
      'perm_call_log_title': 'Call Logs',
      'perm_call_log_desc': 'To manage your driver communications.',
      'allow_permissions': 'Allow Permissions',
      'perm_required_message': 'Location permission is required to proceed.',
      'no_active_job_desc': "You don't have any trips assigned currently. Contact your fleet manager.",
      'primary_driver': 'Primary Driver',
      'wallet_balances': 'Wallet Balances',
      'fuel_balance': 'Fuel Balance',
      'fastag_balance': 'Fastag Balance',
      'vehicle_health': 'Vehicle Health',
      'fuel_level': 'FUEL LEVEL',
      'def_level': 'DEF LEVEL',
      'liters': 'Liters',
      'route_progress': 'Route Progress',
      'distance_remaining': 'Distance Remaining',
      'trip_in_progress': 'Trip In Progress',
      'select_language': 'Select Language',
      'distance_covered': 'Distance Covered',
    },
    'hi': {
      'login_title': 'ड्राइवारा ड्राइवर',
      'login_subtitle': 'लॉगिन करने के लिए अपना नंबर दर्ज करें',
      'phone_hint': 'मोबाइल नंबर',
      'get_started': 'शुरू करें',
      'verify_otp': 'सत्यापित करें और लॉगिन करें',
      'otp_sent_to': 'भेजा गया',
      'enter_otp': 'ओटीपी दर्ज करें',
      'active_job': 'सक्रिय ट्रिप',
      'no_active_job': 'कोई सक्रिय ट्रिप नहीं',
      'logout': 'लॉग आउट',
      'start_trip': 'यात्रा शुरू करें',
      'end_trip': 'यात्रा समाप्त करें',
      'view_route': 'रूट प्लान देखें',
      'add_expense': 'खर्च जोड़ें',
      'welcome': 'स्वागत है',
      'you_are_all_set': 'आप पूरी तरह तैयार हैं!',
      'permissions_title': 'अनुमतियां',
      'permissions_subtitle': 'आपकी पहचान सत्यापित करने और आपकी यात्राओं को ट्रैक करने के लिए, Drivara को निम्नलिखित की आवश्यकता है:',
      'perm_location_title': 'लोकेशन एक्सेस',
      'perm_location_desc': 'आपकी यात्राओं को ट्रैक करने और माइलेज की गणना करने के लिए आवश्यक है।',
      'perm_contacts_title': 'संपर्क (Contacts)',
      'perm_contacts_desc': 'अपने नेटवर्क को सिंक करने और संदर्भों को सत्यापित करने के लिए।',
      'perm_sms_title': 'एसएमएस (SMS) एक्सेस',
      'perm_sms_desc': 'खाता सत्यापन और लेनदेन अलर्ट के लिए।',
      'perm_call_log_title': 'कॉल लॉग्स',
      'perm_call_log_desc': 'अपने ड्राइवर संचार को प्रबंधित करने के लिए।',
      'allow_permissions': 'अनुमति दें',
      'perm_required_message': 'आगे बढ़ने के लिए लोकेशन अनुमति आवश्यक है।',
      'no_active_job_desc': 'वर्तमान में आपको कोई ट्रिप असाइन नहीं की गई है। अपने फ्लीट मैनेजर से संपर्क करें।',
      'primary_driver': 'प्राथमिक ड्राइवर',
      'wallet_balances': 'वॉलेट बैलेंस',
      'fuel_balance': 'ईंधन शेष',
      'fastag_balance': 'फास्टैग शेष',
      'vehicle_health': 'वाहन स्वास्थ्य',
      'fuel_level': 'ईंधन स्तर',
      'def_level': 'DEF स्तर',
      'liters': 'लीटर',
      'route_progress': 'रूट प्रगति',
      'distance_remaining': 'शेष दूरी',
      'trip_in_progress': 'यात्रा प्रगति पर है',
      'select_language': 'भाषा चुनें',
      'distance_covered': 'तय की गई दूरी',
    },
    'te': { // Telugu
      'login_title': 'Drivara Driver',
      'login_subtitle': 'Enter your number to login',
      'phone_hint': 'మొబైల్ నంబర్',
      'get_started': 'ప్రారంభించండి',
      'verify_otp': 'Verify & Login',
      'otp_sent_to': 'Sent to',
      'enter_otp': 'OTP నమోదు చేయండి',
      'active_job': 'Active Job',
      'no_active_job': 'యాక్టివ్ ట్రిప్‌లు లేవు',
      'logout': 'లాగ్ అవుట్',
      'start_trip': 'ట్రిప్ ప్రారంభించండి',
      'end_trip': 'End Trip',
      'view_route': 'View Route Plan',
      'add_expense': 'Add Expense',
      'welcome': 'స్వాగతం',
      'you_are_all_set': 'You are all set!',
      'permissions_title': 'అనుమతులు',
      'permissions_subtitle': 'మీ గుర్తింపును ధృవీకరించడానికి మరియు మీ ట్రిప్పులను ట్రాక్ చేయడానికి, Drivaraకి ఈ క్రింది యాక్సెస్ అవసరం:',
      'perm_location_title': 'లొకేషన్ యాక్సెస్',
      'perm_location_desc': 'మీ ట్రిప్పులను ట్రాక్ చేయడానికి మరియు మైలేజీని లెక్కించడానికి అవసరం.',
      'perm_contacts_title': 'పరిచయాలు (Contacts)',
      'perm_contacts_desc': 'మీ నెట్‌వర్క్‌ని సింక్ చేయడానికి.',
      'perm_sms_title': 'SMS యాక్సెస్',
      'perm_sms_desc': 'ఖాతా ధృవీకరణ కోసం.',
      'perm_call_log_title': 'కాల్ లాగ్స్',
      'perm_call_log_desc': 'మీ కమ్యూనికేషన్‌లను నిర్వహించడానికి.',
      'allow_permissions': 'అనుమతించండి',
      'perm_required_message': 'ముందుకు వెళ్లడానికి లొకేషన్ అనుమతి అవసరం.',
      'no_active_job_desc': 'ప్రస్తుతం మీకు ఎలాంటి ట్రిప్పులు కేటాయించబడలేదు. మీ ఫ్లీట్ మేనేజర్‌ని సంప్రదించండి.',
      'primary_driver': 'ప్రైమరీ డ్రైవర్',
      'wallet_balances': 'వాలెట్ బ్యాలెన్స్',
      'fuel_balance': 'ఫ్యూయల్ బ్యాలెన్స్',
      'fastag_balance': 'ఫాస్టాగ్‌ బ్యాలెన్స్',
      'vehicle_health': 'వాహన ఆరోగ్యం',
      'fuel_level': 'ఫ్యూయల్ లెవెల్',
      'def_level': 'DEF లెవెల్',
      'liters': 'లీటర్లు',
      'route_progress': 'రూట్ ప్రోగ్రెస్',
      'distance_remaining': 'మిగిలిన దూరం',
      'trip_in_progress': 'ట్రిప్ జరుగుతోంది',
      'select_language': 'భాషను ఎంచుకోండి',
      'distance_covered': 'ప్రయాణించిన దూరం',
    },
    'ml': { // Malayalam
      'login_title': 'Drivara Driver',
      'login_subtitle': 'Enter your number to login',
      'phone_hint': 'മൊബൈൽ നമ്പർ',
      'get_started': 'തുടങ്ങുക',
      'verify_otp': 'Verify & Login',
      'otp_sent_to': 'Sent to',
      'enter_otp': 'OTP നൽകുക',
      'active_job': 'Active Job',
      'no_active_job': 'സജീവ യാത്രകളൊന്നുമില്ല',
      'logout': 'ലോഗ് ഔട്ട്',
      'start_trip': 'യാത്ര തുടങ്ങുക',
      'end_trip': 'End Trip',
      'view_route': 'View Route Plan',
      'add_expense': 'Add Expense',
      'welcome': 'സ്വാഗതം',
      'you_are_all_set': 'You are all set!',
      'permissions_title': ' അനുമതികൾ',
      'permissions_subtitle': 'നിങ്ങളുടെ ഐഡന്റിറ്റി പരിശോധിച്ചുറപ്പിക്കുന്നതിനും യാത്രകൾ ട്രാക്കുചെയ്യുന്നതിനും, Drivara-യ്ക്ക് ഇനിപ്പറയുന്നവ ആവശ്യമാണ്:',
      'perm_location_title': 'ലൊക്കേഷൻ ആക്സസ്',
      'perm_location_desc': 'യാത്രകൾ ട്രാക്കുചെയ്യുന്നതിന്.',
      'perm_contacts_title': 'കോൺടാക്റ്റുകൾ',
      'perm_contacts_desc': 'നിങ്ങളുടെ നെറ്റ്‌വർക്ക് സമന്വയിപ്പിക്കാൻ.',
      'perm_sms_title': 'SMS ആക്സസ്',
      'perm_sms_desc': 'അക്കൗണ്ട് പരിശോധിച്ചുറപ്പിക്കുന്നതിന്.',
      'perm_call_log_title': 'കോൾ ലോഗുകൾ',
      'perm_call_log_desc': 'ആശയവിനിമയങ്ങൾ നിയന്ത്രിക്കാൻ.',
      'allow_permissions': 'അനുവദിക്കുക',
      'perm_required_message': 'മുന്നോട്ട് പോകാൻ ലൊക്കേഷൻ അനുമതി ആവശ്യമാണ്.',
      'no_active_job_desc': 'നിങ്ങൾക്ക് നിലവിൽ യാത്രകളൊന്നും നൽകിയിട്ടില്ല. ഫ്ലീറ്റ് മാനേജറുമായി ബന്ധപ്പെടുക.',
      'primary_driver': 'പ്രൈമറി ഡ്രൈവർ',
      'wallet_balances': 'വാലറ്റ് ബാലൻസ്',
      'fuel_balance': 'ഇന്ധന ബാലൻസ്',
      'fastag_balance': 'ഫാസ്റ്റാഗ് ബാലൻസ്',
      'vehicle_health': 'വാഹനത്തിന്റെ അവസ്ഥ',
      'fuel_level': 'ഇന്ധന നില',
      'def_level': 'DEF നില',
      'liters': 'ലിറ്റർ',
      'route_progress': 'യാത്രാ പുരോഗതി',
      'distance_remaining': 'ശേഷിക്കുന്ന ദൂരം',
      'trip_in_progress': 'യാത്ര പുരോഗമിക്കുന്നു',
      'select_language': 'ഭാഷ തിരഞ്ഞെടുക്കുക',
      'distance_covered': 'പിന്നിട്ട ദൂരം',
    },
    'kn': { // Kannada
      'login_title': 'Drivara Driver',
      'login_subtitle': 'Enter your number to login',
      'phone_hint': 'ಮೊಬೈಲ್ ಸಂಖ್ಯೆ',
      'get_started': 'ಪ್ರಾರಂಭಿಸಿ',
      'verify_otp': 'Verify & Login',
      'otp_sent_to': 'Sent to',
      'enter_otp': 'OTP ನಮೂದಿಸಿ',
      'active_job': 'Active Job',
      'no_active_job': 'ಯಾವುದೇ ಸಕ್ರಿಯ ಟ್ರಿಪ್‌ಗಳಿಲ್ಲ',
      'logout': 'ಲಾಗ್ ಔಟ್',
      'start_trip': 'ಟ್ರಿಪ್ ಪ್ರಾರಂಭಿಸಿ',
      'end_trip': 'End Trip',
      'view_route': 'View Route Plan',
      'add_expense': 'Add Expense',
      'welcome': 'ಸ್ವಾಗತ',
      'you_are_all_set': 'You are all set!',
       'permissions_title': 'ಅನುಮತಿಗಳು',
      'permissions_subtitle': 'ನಿಮ್ಮ ಗುರುತನ್ನು ಪರಿಶೀಲಿಸಲು ಮತ್ತು ಟ್ರಿಪ್‌ಗಳನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಲು, Drivara ಗೆ ಈ ಕೆಳಗಿನವುಗಳ ಅಗತ್ಯವಿದೆ:',
      'perm_location_title': 'ಸ್ಥಳದ (Location) ಪ್ರವೇಶ',
      'perm_location_desc': 'ಟ್ರಿಪ್‌ಗಳನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಲು ಮತ್ತು ಮೈಲೇಜ್ ಲೆಕ್ಕಹಾಕಲು.',
      'perm_contacts_title': 'ಸಂಪರ್ಕಗಳು (Contacts)',
      'perm_contacts_desc': 'ನಿಮ್ಮ ನೆಟ್‌ವರ್ಕ್ ಸಿಂಕ್ ಮಾಡಲು.',
      'perm_sms_title': 'SMS ಪ್ರವೇಶ',
      'perm_sms_desc': 'ಖಾತೆ ಪರಿಶೀಲನೆಗಾಗಿ.',
      'perm_call_log_title': 'ಕರೆದ ದಾಖಲೆಗಳು (Call Logs)',
      'perm_call_log_desc': 'ಚಾಲಕ ಸಂವಹನಗಳನ್ನು ನಿರ್ವಹಿಸಲು.',
      'allow_permissions': 'ಅನುಮತಿಸಿ',
      'perm_required_message': 'ಮುಂದುವರಿಯಲು ಸ್ಥಳದ ಅನುಮತಿ ಅಗತ್ಯವಿದೆ.',
      'no_active_job_desc': 'ಪ್ರಸ್ತುತ ನಿಮಗೆ ಯಾವುದೇ ಟ್ರಿಪ್‌ಗಳನ್ನು ನಿಯೋಜಿಸಲಾಗಿಲ್ಲ. ಫ್ಲೀಟ್ ಮ್ಯಾನೇಜರ್ ಅನ್ನು ಸಂಪರ್ಕಿಸಿ.',
      'primary_driver': 'ಪ್ರಾಥಮಿಕ ಚಾಲಕ',
      'wallet_balances': 'ವ್ಯಾಲೆಟ್ ಬಾಕಿ',
      'fuel_balance': 'ಇಂಧನ ಬಾಕಿ',
      'fastag_balance': 'ಫಾಸ್ಟ್ಯಾಗ್ ಬಾಕಿ',
      'vehicle_health': 'ವಾಹನದ ಆರೋಗ್ಯ',
      'fuel_level': 'ಇಂಧನ ಮಟ್ಟ',
      'def_level': 'DEF ಮಟ್ಟ',
      'liters': 'ಲೀಟರ್',
      'route_progress': 'ಮಾರ್ಗ ಪ್ರಗತಿ',
      'distance_remaining': 'ಉಳಿದಿರುವ ದೂರ',
      'trip_in_progress': 'ಟ್ರಿಪ್ ಪ್ರಗತಿಯಲ್ಲಿದೆ',
      'select_language': 'ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
      'distance_covered': 'ಕ್ರಮಿಸಿದ ದೂರ',
    },
    'ta': { // Tamil
      'login_title': 'Drivara Driver',
      'login_subtitle': 'Enter your number to login',
      'phone_hint': 'மொபைல் எண்',
      'get_started': 'தொடங்கவும்',
      'verify_otp': 'Verify & Login',
      'otp_sent_to': 'Sent to',
      'enter_otp': 'OTP ஐ உள்ளிடவும்',
      'active_job': 'Active Job',
      'no_active_job': 'செயலில் உள்ள பயணங்கள் இல்லை',
      'logout': 'வெளியேறு',
      'start_trip': 'பயணத்தைத் தொடங்கவும்',
      'end_trip': 'End Trip',
      'view_route': 'View Route Plan',
      'add_expense': 'Add Expense',
      'welcome': 'நல்வரவு',
      'you_are_all_set': 'You are all set!',
      'permissions_title': 'அனுமதிகள்',
      'permissions_subtitle': 'உங்கள் அடையாளத்தைச் சரிபார்க்கவும் பயணங்களைக் கண்காணிக்கவும், Drivara விற்கு பின்வருவன தேவை:',
      'perm_location_title': 'இருப்பிட அணுகல்',
      'perm_location_desc': 'பயணங்களைக் கண்காணிக்கவும் மைலேஜைக் கணக்கிடவும் தேவை.',
      'perm_contacts_title': 'தொடர்புகள்',
      'perm_contacts_desc': 'உங்கள் நெட்வொர்க்கை ஒத்திசைக்க.',
      'perm_sms_title': 'SMS அணுகல்',
      'perm_sms_desc': 'கணக்கு சரிபார்ப்பிற்கு.',
      'perm_call_log_title': 'அழைப்பு பதிவுகள்',
      'perm_call_log_desc': 'தொடர்புகளை நிர்வகிக்க.',
      'allow_permissions': 'அனுಮதிக்கவும்',
      'perm_required_message': 'தொடர இருப்பிட அனுமதி தேவை.',
      'no_active_job_desc': 'தற்போது உங்களுக்கு எந்த பயணங்களும் ஒதுக்கப்படவில்லை. ஃப்ளீட் மேலாளரைத் தொடர்பு கொள்ளவும்.',
      'primary_driver': 'முதன்மை ஓட்டுநர்',
      'wallet_balances': 'பணப்பை இருப்பு',
      'fuel_balance': 'எரிபொருள் இருப்பு',
      'fastag_balance': 'பாஸ்டேக் இருப்பு',
      'vehicle_health': 'வாகன நிலை',
      'fuel_level': 'எரிபொருள் அளவு',
      'def_level': 'DEF அளவு',
      'liters': 'லிட்டர்',
      'route_progress': 'பயண முன்னேற்றம்',
      'distance_remaining': 'மீதமுள்ள தூரம்',
      'trip_in_progress': 'பயணம் நடைபெறுகிறது',
      'select_language': 'மொழியைத் தேர்ந்தெடுக்கவும்',
      'distance_covered': 'கடந்து வந்த தூரம்',
    },
  };

  String t(String key) {
    return _localizedStrings[_locale.languageCode]?[key] ?? key;
  }
}
