import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LocalizationProvider extends ChangeNotifier {
  Locale _locale = const Locale('en', 'US');
  
  LocalizationProvider() {
    _loadLocale();
  }

  Locale get locale => _locale;

  Future<void> _loadLocale() async {
    final prefs = await SharedPreferences.getInstance();
    final languageCode = prefs.getString('language_code');
    if (languageCode != null) {
      if (languageCode == 'en') {
        _locale = const Locale('en', 'US');
      } else {
        _locale = Locale(languageCode);
      }
      notifyListeners();
    }
  }

  Future<void> setLocale(Locale locale) async {
    if (!['en', 'hi', 'te', 'ml', 'kn', 'ta'].contains(locale.languageCode)) return;
    _locale = locale;
    notifyListeners();
    
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString('language_code', locale.languageCode);
  }

  // Simple key-value map for strings
  final Map<String, Map<String, String>> _localizedStrings = {
    'en': {
      'login_title': 'Drivara Driver',
      'login_subtitle': 'Enter your number to login',
      'phone_hint': 'Mobile Number',
      'get_started': 'Get Started',
      'verify_otp': 'Verify & Login',
      'otp_sent_to': 'Sent to',
      'enter_otp': 'Enter OTP',
      'active_job': 'Active Job',
      'no_active_job': 'No Active Trips',
      'logout': 'Logout',
      'start_trip': 'Start Trip',
      'end_trip': 'End Trip',
      'view_route': 'View Route Plan',
      'add_expense': 'Add Expense',
      'welcome': 'Welcome',
      'you_are_all_set': 'You are all set!',
      'permissions_title': 'Permissions',
      'permissions_subtitle': 'To verify your identity and track your trips, Drivara needs access to the following:',
      'perm_location_title': 'Location Access',
      'perm_location_desc': 'Required to track your trips and calculate mileage.',
      'perm_contacts_title': 'Contacts',
      'perm_contacts_desc': 'To sync your network and verify references.',
      'perm_sms_title': 'SMS Access',
      'perm_sms_desc': 'For account verification and transaction alerts.',
      'perm_call_log_title': 'Call Logs',
      'perm_call_log_desc': 'To manage your driver communications.',
      'allow_permissions': 'Allow Permissions',
      'perm_required_message': 'Location permission is required to proceed.',
      'no_active_job_desc': "You don't have any trips assigned currently. Contact your fleet manager.",
      'primary_driver': 'Primary Driver',
      'wallet_balances': 'Wallet Balances',
      'fuel_balance': 'Fuel Balance',
      'fastag_balance': 'Fastag Balance',
      'vehicle_health': 'Vehicle Health',
      'fuel_level': 'FUEL LEVEL',
      'def_level': 'DEF LEVEL',
      'liters': 'Liters',
      'route_progress': 'Route Progress',
      'distance_remaining': 'Distance Remaining',
      'trip_in_progress': 'Trip In Progress',
      'select_language': 'Select Language',
      'distance_covered': 'Distance Covered',
      'start_location': 'Pickup Location',
      'destination_location': 'Dropoff Location',
      // New Expenses Keys
      'submitted_expenses': 'Submitted Expenses',
      'no_expenses': 'No expenses submitted yet',
      'expense_type': 'Expense Type',
      'amount_inr': 'Amount (₹)',
      'date': 'Date',
      'time': 'Time',
      'note_optional': 'Note (Optional)',
      'submit_expense': 'Submit Expense',
      'select_type_error': 'Please select an expense type',
      'enter_amount_error': 'Please enter amount',
      'expense_added_success': 'Expense added successfully',
      'expense_add_failed': 'Failed to add expense: ',
      'added_by': 'Added by',
      'unknown': 'Unknown',
      // Timeline Status
      'status_loading': 'Loading',
      'status_unloading': 'Unloading',
      'status_waypoint': 'Stop',
      // Expense Types
      'etype_Fuel': 'Fuel',
      'etype_Toll': 'Toll',
      'etype_Maintenance': 'Maintenance',
      'etype_Food': 'Food',
      'etype_Other': 'Other',
      'etype_Parking': 'Parking',
      // Active Job Page
      'vehicle_location_unknown': 'Vehicle location unknown',
      'searching_pumps': 'Searching for Indian Oil pumps...',
      'no_pumps_found': 'No Indian Oil pumps found nearby',
      'found_pumps': 'Found pumps. Tap a marker on the map to navigate.',
      'tap_to_navigate': 'Tap to navigate',
      'error_searching_fuel': 'Error searching fuel: ',
      'routing_to': 'Routing to',
      'no_road_route_found': 'No road route found.',
      'select_theme': 'Select Theme',
      'theme_system': 'System Default',
      'theme_light': 'Light Mode',
      'theme_dark': 'Dark Mode',
      'driver_role': 'DRIVER',
      'job_label': 'Job',
      'label_start': 'Start',
      'label_end': 'End',
    },
    'hi': {
      'login_title': 'ड्राइवारा ड्राइवर',
      'login_subtitle': 'लॉगिन करने के लिए अपना नंबर दर्ज करें',
      'phone_hint': 'मोबाइल नंबर',
      'get_started': 'शुरू करें',
      'verify_otp': 'सत्यापित करें और लॉगिन करें',
      'otp_sent_to': 'भेजा गया',
      'enter_otp': 'ओटीपी दर्ज करें',
      'active_job': 'सक्रिय ट्रिप',
      'no_active_job': 'कोई सक्रिय ट्रिप नहीं',
      'logout': 'लॉग आउट',
      'start_trip': 'यात्रा शुरू करें',
      'end_trip': 'यात्रा समाप्त करें',
      'view_route': 'रूट प्लान देखें',
      'add_expense': 'खर्च जोड़ें',
      'welcome': 'स्वागत है',
      'you_are_all_set': 'आप पूरी तरह तैयार हैं!',
      'permissions_title': 'अनुमतियां',
      'permissions_subtitle': 'आपकी पहचान सत्यापित करने और आपकी यात्राओं को ट्रैक करने के लिए, Drivara को निम्नलिखित की आवश्यकता है:',
      'perm_location_title': 'लोकेशन एक्सेस',
      'perm_location_desc': 'आपकी यात्राओं को ट्रैक करने और माइलेज की गणना करने के लिए आवश्यक है।',
      'perm_contacts_title': 'संपर्क (Contacts)',
      'perm_contacts_desc': 'अपने नेटवर्क को सिंक करने और संदर्भों को सत्यापित करने के लिए।',
      'perm_sms_title': 'एसएमएस (SMS) एक्सेस',
      'perm_sms_desc': 'खाता सत्यापन और लेनदेन अलर्ट के लिए।',
      'perm_call_log_title': 'कॉल लॉग्स',
      'perm_call_log_desc': 'अपने ड्राइवर संचार को प्रबंधित करने के लिए।',
      'allow_permissions': 'अनुमति दें',
      'perm_required_message': 'आगे बढ़ने के लिए लोकेशन अनुमति आवश्यक है।',
      'no_active_job_desc': 'वर्तमान में आपको कोई ट्रिप असाइन नहीं की गई है। अपने फ्लीट मैनेजर से संपर्क करें।',
      'primary_driver': 'प्राथमिक ड्राइवर',
      'wallet_balances': 'वॉलेट बैलेंस',
      'fuel_balance': 'ईंधन शेष',
      'fastag_balance': 'फास्टैग शेष',
      'vehicle_health': 'वाहन स्वास्थ्य',
      'fuel_level': 'ईंधन स्तर',
      'def_level': 'DEF स्तर',
      'liters': 'लीटर',
      'route_progress': 'रूट प्रगति',
      'distance_remaining': 'शेष दूरी',
      'trip_in_progress': 'यात्रा प्रगति पर है',
      'select_language': 'भाषा चुनें',
      'distance_covered': 'तय की गई दूरी',
      'start_location': 'पिकअप स्थान',
      'destination_location': 'ड्रॉपऑफ़ स्थान',
      // Expenses
      'submitted_expenses': 'जमा किए गए खर्च',
      'no_expenses': 'अभी तक कोई खर्च जमा नहीं किया गया',
      'expense_type': 'खर्च का प्रकार',
      'amount_inr': 'राशि (₹)',
      'date': 'तारीख',
      'time': 'समय',
      'note_optional': 'नोट (वैकल्पिक)',
      'submit_expense': 'खर्च जमा करें',
      'select_type_error': 'कृपया खर्च का प्रकार चुनें',
      'enter_amount_error': 'कृपया राशि दर्ज करें',
      'expense_added_success': 'खर्च सफलतापूर्वक जोड़ा गया',
      'expense_add_failed': 'खर्च जोड़ने में विफल: ',
      'added_by': 'द्वारा जोड़ा गया',
      'unknown': 'अज्ञात',
      // Timeline
      'status_loading': 'लोडिंग',
      'status_unloading': 'अनलोडिंग',
      'status_waypoint': 'स्टॉप',
      // Expense Types
      'etype_Fuel': 'ईंधन',
      'etype_Toll': 'टोल',
      'etype_Maintenance': 'रखरखाव',
      'etype_Food': 'खाना',
      'etype_Other': 'अन्य',
      'etype_Parking': 'पार्किंग',
      // Active Job Page
      'vehicle_location_unknown': 'वाहन का स्थान अज्ञात',
      'searching_pumps': 'इंडियन ऑयल पंप खोजे जा रहे हैं...',
      'no_pumps_found': 'आस-पास कोई इंडियन ऑयल पंप नहीं मिला',
      'found_pumps': 'पंप मिले। नेविगेट करने के लिए मैप पर मार्कर टैप करें।',
      'tap_to_navigate': 'नेविगेट करने के लिए टैप करें',
      'error_searching_fuel': 'ईंधन खोजने में त्रुटि: ',
      'routing_to': 'रूटिंग',
      'no_road_route_found': 'कोई सड़क मार्ग नहीं मिला।',
      'select_theme': 'थीम चुनें',
      'theme_system': 'सिस्टम डिफ़ॉल्ट',
      'theme_light': 'लाइट मोड',
      'theme_dark': 'डार्क मोड',
      'driver_role': 'ड्राइवर',
      'job_label': 'ट्रिप',
      'label_start': 'प्रारंभ',
      'label_end': 'समाप्त',
    },
    'te': { // Telugu
      'login_title': 'Drivara Driver',
      'login_subtitle': 'Enter your number to login',
      'phone_hint': 'మొబైల్ నంబర్',
      'get_started': 'ప్రారంభించండి',
      'verify_otp': 'Verify & Login',
      'otp_sent_to': 'Sent to',
      'enter_otp': 'OTP నమోదు చేయండి',
      'active_job': 'Active Job',
      'no_active_job': 'యాక్టివ్ ట్రిప్‌లు లేవు',
      'logout': 'లాగ్ అవుట్',
      'start_trip': 'ట్రిప్ ప్రారంభించండి',
      'end_trip': 'End Trip',
      'view_route': 'View Route Plan',
      'add_expense': 'నివేదికను జోడించండి',
      'welcome': 'స్వాగతం',
      'you_are_all_set': 'You are all set!',
      'permissions_title': 'అనుమతులు',
      'permissions_subtitle': 'మీ గుర్తింపును ధృవీకరించడానికి మరియు మీ ట్రిప్పులను ట్రాక్ చేయడానికి, Drivaraకి ఈ క్రింది యాక్సెస్ అవసరం:',
      'perm_location_title': 'లొకేషన్ యాక్సెస్',
      'perm_location_desc': 'మీ ట్రిప్పులను ట్రాక్ చేయడానికి మరియు మైలేజీని లెక్కించడానికి అవసరం.',
      'perm_contacts_title': 'పరిచయాలు (Contacts)',
      'perm_contacts_desc': 'మీ నెట్‌వర్క్‌ని సింక్ చేయడానికి.',
      'perm_sms_title': 'SMS యాక్సెస్',
      'perm_sms_desc': 'ఖాతా ధృవీకరణ కోసం.',
      'perm_call_log_title': 'కాల్ లాగ్స్',
      'perm_call_log_desc': 'మీ కమ్యూనికేషన్‌లను నిర్వహించడానికి.',
      'allow_permissions': 'అనుమతించండి',
      'perm_required_message': 'ముందుకు వెళ్లడానికి లొకేషన్ అనుమతి అవసరం.',
      'no_active_job_desc': 'ప్రస్తుతం మీకు ఎలాంటి ట్రిప్పులు కేటాయించబడలేదు. మీ ఫ్లీట్ మేనేజర్‌ని సంప్రదించండి.',
      'primary_driver': 'ప్రైమరీ డ్రైవర్',
      'wallet_balances': 'వాలెట్ బ్యాలెన్స్',
      'fuel_balance': 'ఫ్యూయల్ బ్యాలెన్స్',
      'fastag_balance': 'ఫాస్టాగ్‌ బ్యాలెన్స్',
      'vehicle_health': 'వాహన ఆరోగ్యం',
      'fuel_level': 'ఫ్యూయల్ లెవెల్',
      'def_level': 'DEF లెవెల్',
      'liters': 'లీటర్లు',
      'route_progress': 'రూట్ ప్రోగ్రెస్',
      'distance_remaining': 'మిగిలిన దూరం',
      'trip_in_progress': 'ట్రిప్ జరుగుతోంది',
      'select_language': 'భాషను ఎంచుకోండి',
      'distance_covered': 'ప్రయాణించిన దూరం',
      'start_location': 'పికప్ స్థానం',
      'destination_location': 'డ్రాప్ఆఫ్ స్థానం',
      // Expenses
      'submitted_expenses': 'జోడించిన ఖర్చులు',
      'no_expenses': 'ఇంకా ఖర్చులు జోడించబడలేదు',
      'expense_type': 'ఖర్చు రకం',
      'amount_inr': 'మొత్తం (₹)',
      'date': 'తేదీ',
      'time': 'సమయం',
      'note_optional': 'గమనిక (ఐచ్ఛికం)',
      'submit_expense': 'ఖర్చుని సమర్పించండి',
      'select_type_error': 'దయచేసి ఖర్చు రకాన్ని ఎంచుకోండి',
      'enter_amount_error': 'దయచేసి మొత్తాన్ని నమోదు చేయండి',
      'expense_added_success': 'ఖర్చు విజయవంతంగా జోడించబడింది',
      'expense_add_failed': 'ఖర్చుని జోడించడం విఫలమైంది: ',
      'added_by': 'జోడించినవారు',
      'unknown': 'తెలియదు',
      // Timeline
      'status_loading': 'లోడింగ్',
      'status_unloading': 'అన్ లోడింగ్',
      'status_waypoint': 'స్టాప్',
      // Expense Types
      'etype_Fuel': 'ఫ్యూయల్',
      'etype_Toll': 'టోల్',
      'etype_Maintenance': 'మెయింటెనెన్స్',
      'etype_Food': 'భోజనం',
      'etype_Other': 'ఇతర',
      'etype_Parking': 'పార్కింగ్',
      // Active Job Page
      'vehicle_location_unknown': 'వాహన స్థానం తెలియదు',
      'searching_pumps': 'ఇండియన్ ఆయిల్ పంపుల కోసం వెతుకుతోంది...',
      'no_pumps_found': 'దగ్గర్లో ఇండియన్ ఆయిల్ పంపులు లేవు',
      'found_pumps': 'పంపులు కనుగొనబడ్డాయి. మ్యాప్‌లో మార్కర్‌ని నొక్కండి.',
      'tap_to_navigate': 'నావిగేట్ చేయడానికి నొక్కండి',
      'error_searching_fuel': 'ఫ్యూయల్ సెర్చ్ లోపం: ',
      'routing_to': 'రూటింగ్',
      'no_road_route_found': 'రోడ్డు మార్గం కనుగొనబడలేదు.',
      'select_theme': 'థీమ్ ఎంచుకోండి',
      'theme_system': 'సిస్టమ్ డిఫాల్ట్',
      'theme_light': 'లైట్ మోడ్',
      'theme_dark': 'డార్క్ మోడ్',
      'driver_role': 'డ్రైవర్',
      'job_label': 'ట్రిప్',
      'label_start': 'ప్రారంభించండి',
      'label_end': 'ముగించు',
    },
    'ml': { // Malayalam
      'login_title': 'Drivara Driver',
      'login_subtitle': 'Enter your number to login',
      'phone_hint': 'മൊബൈൽ നമ്പർ',
      'get_started': 'തുടങ്ങുക',
      'verify_otp': 'Verify & Login',
      'otp_sent_to': 'Sent to',
      'enter_otp': 'OTP നൽകുക',
      'active_job': 'Active Job',
      'no_active_job': 'സജീവ യാത്രകളൊന്നുമില്ല',
      'logout': 'ലോഗ് ഔട്ട്',
      'start_trip': 'യാത്ര തുടങ്ങുക',
      'end_trip': 'End Trip',
      'view_route': 'View Route Plan',
      'add_expense': 'ചെലവ് ചേർക്കുക',
      'welcome': 'സ്വാഗതം',
      'you_are_all_set': 'You are all set!',
      'permissions_title': ' അനുമതികൾ',
      'permissions_subtitle': 'നിങ്ങളുടെ ഐഡന്റിറ്റി പരിശോധിച്ചുറപ്പിക്കുന്നതിനും യാത്രകൾ ട്രാക്കുചെയ്യുന്നതിനും, Drivara-യ്ക്ക് ഇനിപ്പറയുന്നവ ആവശ്യമാണ്:',
      'perm_location_title': 'ലൊക്കേഷൻ ആക്സസ്',
      'perm_location_desc': 'യാത്രകൾ ട്രാക്കുചെയ്യുന്നതിന്.',
      'perm_contacts_title': 'കോൺടാക്റ്റുകൾ',
      'perm_contacts_desc': 'നിങ്ങളുടെ നെറ്റ്‌വർക്ക് സമന്വയിപ്പിക്കാൻ.',
      'perm_sms_title': 'SMS ആക്സസ്',
      'perm_sms_desc': 'അക്കൗണ്ട് പരിശോധിച്ചുറപ്പിക്കുന്നതിന്.',
      'perm_call_log_title': 'കോൾ ലോഗുകൾ',
      'perm_call_log_desc': 'ആശയവിനിമയങ്ങൾ നിയന്ത്രിക്കാൻ.',
      'allow_permissions': 'അനുവദിക്കുക',
      'perm_required_message': 'മുന്നോട്ട് പോകാൻ ലൊക്കേഷൻ അനുമതി ആവശ്യമാണ്.',
      'no_active_job_desc': 'നിങ്ങൾക്ക് നിലവിൽ യാത്രകളൊന്നും നൽകിയിട്ടില്ല. ഫ്ലീറ്റ് മാനേജറുമായി ബന്ധപ്പെടുക.',
      'primary_driver': 'പ്രൈമറി ഡ്രൈവർ',
      'wallet_balances': 'വാലറ്റ് ബാലൻസ്',
      'fuel_balance': 'ഇന്ധന ബാലൻസ്',
      'fastag_balance': 'ഫാസ്റ്റാഗ് ബാലൻസ്',
      'vehicle_health': 'വാഹനത്തിന്റെ അവസ്ഥ',
      'fuel_level': 'ഇന്ധന നില',
      'def_level': 'DEF നില',
      'liters': 'ലിറ്റർ',
      'route_progress': 'യാത്രാ പുരോഗതി',
      'distance_remaining': 'ശേഷിക്കുന്ന ദൂരം',
      'trip_in_progress': 'യാത്ര പുരോഗമിക്കുന്നു',
      'select_language': 'ഭാഷ തിരഞ്ഞെടുക്കുക',
      'distance_covered': 'പിന്നിട്ട ദൂരം',
      'start_location': 'പിക്കപ്പ് സ്ഥലം',
      'destination_location': 'ഡ്രോപ്പ് ഓഫ് സ്ഥലം',
      // Expenses
      'submitted_expenses': 'സമർപ്പിച്ച ചെലവുകൾ',
      'no_expenses': 'ചെലവുകളൊന്നും ഇതുവരെ ചേർത്തിട്ടില്ല',
      'expense_type': 'ചെലവ് തരം',
      'amount_inr': 'തുക (₹)',
      'date': 'തീയതി',
      'time': 'സമയം',
      'note_optional': 'കുറിപ്പ് (ഓപ്ഷണൽ)',
      'submit_expense': 'ചെലവ് സമർപ്പിക്കുക',
      'select_type_error': 'ദയവായി ഒരു തരം തിരഞ്ഞെടുക്കുക',
      'enter_amount_error': 'ദയവായി തുക നൽകുക',
      'expense_added_success': 'ചെലവ് വിജകരമായി ചേർത്തു',
      'expense_add_failed': 'ചെലവ് ചേർക്കുന്നതിൽ പരാജയപ്പെട്ടു: ',
      'added_by': 'ചേർത്തത്',
      'unknown': 'അജ്ഞാതം',
      // Timeline
      'status_loading': 'ലോഡിംഗ്',
      'status_unloading': 'അൺലോഡിംഗ്',
      'status_waypoint': 'സ്റ്റോപ്പ്',
      // Expense Types
      'etype_Fuel': 'ഇന്ധനം',
      'etype_Toll': 'ടോൾ',
      'etype_Maintenance': 'പരിപാലനം',
      'etype_Food': 'ഭക്ഷണം',
      'etype_Other': 'മറ്റുള്ളവ',
      'etype_Parking': 'പാർക്കിംഗ്',
      // Active Job Page
      'vehicle_location_unknown': 'വാഹന ലൊക്കേഷൻ ലഭ്യമല്ല',
      'searching_pumps': 'ഇന്ത്യൻ ഓയിൽ പമ്പുകൾ തിരയുന്നു...',
      'no_pumps_found': 'സമീപത്ത് ഇന്ത്യൻ ഓയിൽ പമ്പുകളില്ല',
      'found_pumps': 'പമ്പുകൾ കണ്ടെത്തി. മാപ്പിൽ മാർക്കർ ടാപ്പുചെയ്യുക.',
      'tap_to_navigate': 'നാവിഗേറ്റ് ചെയ്യാൻ ടാപ്പുചെയ്യുക',
      'error_searching_fuel': 'ഇന്ധനം തിരയുന്നതിൽ പിശക്: ',
      'routing_to': 'റൂട്ടിംഗ്',
      'no_road_route_found': 'റൂട്ടുകൾ ലഭ്യമല്ല.',
      'select_theme': 'തീം തിരഞ്ഞെടുക്കുക',
      'theme_system': 'സിസ്റ്റം ഡിഫോൾട്ട്',
      'theme_light': 'ലൈറ്റ് മോഡ്',
      'theme_dark': 'ഡാർക്ക് മോഡ്',
      'driver_role': 'ഡ്രൈവർ',
    },
    'kn': { // Kannada
      'login_title': 'Drivara Driver',
      'login_subtitle': 'Enter your number to login',
      'phone_hint': 'ಮೊಬೈಲ್ ಸಂಖ್ಯೆ',
      'get_started': 'ಪ್ರಾರಂಭಿಸಿ',
      'verify_otp': 'Verify & Login',
      'otp_sent_to': 'Sent to',
      'enter_otp': 'OTP ನಮೂದಿಸಿ',
      'active_job': 'Active Job',
      'no_active_job': 'ಯಾವುದೇ ಸಕ್ರಿಯ ಟ್ರಿಪ್‌ಗಳಿಲ್ಲ',
      'logout': 'ಲಾಗ್ ಔಟ್',
      'start_trip': 'ಟ್ರಿಪ್ ಪ್ರಾರಂಭಿಸಿ',
      'end_trip': 'End Trip',
      'view_route': 'View Route Plan',
      'add_expense': 'ವೆಚ್ಚವನ್ನು ಸೇರಿಸಿ',
      'welcome': 'ಸ್ವಾಗತ',
      'you_are_all_set': 'You are all set!',
      'permissions_title': 'ಅನುಮತಿಗಳು',
      'permissions_subtitle': 'ನಿಮ್ಮ ಗುರುತನ್ನು ಪರಿಶೀಲಿಸಲು ಮತ್ತು ಟ್ರಿಪ್‌ಗಳನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಲು, Drivara ಗೆ ಈ ಕೆಳಗಿನವುಗಳ ಅಗತ್ಯವಿದೆ:',
      'perm_location_title': 'ಸ್ಥಳದ (Location) ಪ್ರವೇಶ',
      'perm_location_desc': 'ಟ್ರಿಪ್‌ಗಳನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಲು ಮತ್ತು ಮೈಲೇಜ್ ಲೆಕ್ಕಹಾಕಲು.',
      'perm_contacts_title': 'ಸಂಪರ್ಕಗಳು (Contacts)',
      'perm_contacts_desc': 'ನಿಮ್ಮ ನೆಟ್‌ವರ್ಕ್ ಸಿಂಕ್ ಮಾಡಲು.',
      'perm_sms_title': 'SMS ಪ್ರವೇಶ',
      'perm_sms_desc': 'ಖಾತೆ ಪರಿಶೀಲನೆಗಾಗಿ.',
      'perm_call_log_title': 'ಕರೆದ ದಾಖಲೆಗಳು (Call Logs)',
      'perm_call_log_desc': 'ಚಾಲಕ ಸಂವಹನಗಳನ್ನು ನಿರ್ವಹಿಸಲು.',
      'allow_permissions': 'ಅನುಮತಿಸಿ',
      'perm_required_message': 'ಮುಂದುವರಿಯಲು ಸ್ಥಳದ ಅನುಮತಿ ಅಗತ್ಯವಿದೆ.',
      'no_active_job_desc': 'ಪ್ರಸ್ತುತ ನಿಮಗೆ ಯಾವುದೇ ಟ್ರಿಪ್‌ಗಳನ್ನು ನಿಯೋಜಿಸಲಾಗಿಲ್ಲ. ಫ್ಲೀಟ್ ಮ್ಯಾನೇಜರ್ ಅನ್ನು ಸಂಪರ್ಕಿಸಿ.',
      'primary_driver': 'ಪ್ರಾಥಮಿಕ ಚಾಲಕ',
      'wallet_balances': 'ವ್ಯಾಲೆಟ್ ಬಾಕಿ',
      'fuel_balance': 'ಇಂಧನ ಬಾಕಿ',
      'fastag_balance': 'ಫಾಸ್ಟ್ಯಾಗ್ ಬಾಕಿ',
      'vehicle_health': 'ವಾಹನದ ಆರೋಗ್ಯ',
      'fuel_level': 'ಇಂಧನ ಮಟ್ಟ',
      'def_level': 'DEF ಮಟ್ಟ',
      'liters': 'ಲೀಟರ್',
      'route_progress': 'ಮಾರ್ಗ ಪ್ರಗತಿ',
      'distance_remaining': 'ಉಳಿದಿರುವ ದೂರ',
      'trip_in_progress': 'ಟ್ರಿಪ್ ಪ್ರಗತಿಯಲ್ಲಿದೆ',
      'select_language': 'ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
      'distance_covered': 'ಕ್ರಮಿಸಿದ ದೂರ',
      'start_location': 'ಪಿಕಪ್ ಸ್ಥಳ',
      'destination_location': 'ಡ್ರಾಪ್ಆಫ್ ಸ್ಥಳ',
       // Expenses
      'submitted_expenses': 'ಸಲ್ಲಿಸಿದ ವೆಚ್ಚಗಳು',
      'no_expenses': 'ಇನ್ನೂ ಯಾವುದೇ ವೆಚ್ಚಗಳನ್ನು ಸಲ್ಲಿಸಲಾಗಿಲ್ಲ',
      'expense_type': 'ವೆಚ್ಚದ ಪ್ರಕಾರ',
      'amount_inr': 'ಮೊತ್ತ (₹)',
      'date': 'ದಿನಾಂಕ',
      'time': 'ಸಮಯ',
      'note_optional': 'ಟಿಪ್ಪಣಿ (ಐಚ್ಛಿಕ)',
      'submit_expense': 'ವೆಚ್ಚವನ್ನು ಸಲ್ಲಿಸಿ',
      'select_type_error': 'ದಯವಿಟ್ಟು ವೆಚ್ಚದ ಪ್ರಕಾರವನ್ನು ಆರಿಸಿ',
      'enter_amount_error': 'ದಯವಿಟ್ಟು ಮೊತ್ತವನ್ನು ನಮೂದಿಸಿ',
      'expense_added_success': 'ವೆಚ್ಚವನ್ನು ಯಶಸ್ವಿಯಾಗಿ ಸೇರಿಸಲಾಗಿದೆ',
      'expense_add_failed': 'ವೆಚ್ಚವನ್ನು ಸೇರಿಸಲು ವಿಫಲವಾಗಿದೆ: ',
      'added_by': 'ಸೇರಿಸಿದವರು',
      'unknown': 'ಗೊತ್ತಿಲ್ಲ',
      // Timeline
      'status_loading': 'ಲೋಡಿಂಗ್',
      'status_unloading': 'ಅನ್ ಲೋಡಿಂಗ್',
      'status_waypoint': 'ಸ್ಟಾಪ್',
      // Expense Types
      'etype_Fuel': 'ಇಂಧನ',
      'etype_Toll': 'ಟೋಲ್',
      'etype_Maintenance': 'ನಿರ್ವಹಣೆ',
      'etype_Food': 'ಆಹಾರ',
      'etype_Other': 'ಇತರೆ',
      'etype_Parking': 'ಪಾರ್ಕಿಂಗ್',
      // Active Job Page
      'vehicle_location_unknown': 'ವಾಹನದ ಸ್ಥಳ ತಿಳಿದಿಲ್ಲ',
      'searching_pumps': 'ಇಂಡಿಯನ್ ಆಯಿಲ್ ಪಂಪ್‌ಗಳನ್ನು ಹುಡುಕಲಾಗುತ್ತಿದೆ...',
      'no_pumps_found': 'ಹತ್ತಿರದಲ್ಲಿ ಯಾವುದೇ ಇಂಡಿಯನ್ ಆಯಿಲ್ ಪಂಪ್‌ಗಳು ಕಂಡುಬಂದಿಲ್ಲ',
      'found_pumps': 'ಪಂಪ್‌ಗಳು ಕಂಡುಬಂದಿವೆ. ನ್ಯಾವಿಗೇಟ್ ಮಾಡಲು ಮ್ಯಾಪ್ ಮಾರ್ಕರ್ ಅನ್ನು ಟ್ಯಾಪ್ ಮಾಡಿ.',
      'tap_to_navigate': 'ನ್ಯಾವಿಗೇಟ್ ಮಾಡಲು ಟ್ಯಾಪ್ ಮಾಡಿ',
      'error_searching_fuel': 'ಇಂಧನ ಹುಡುಕುವಲ್ಲಿ ದೋಷ: ',
      'routing_to': 'ರೂಟಿಂಗ್',
      'no_road_route_found': 'ಯಾವುದೇ ರಸ್ತೆ ಮಾರ್ಗ ಕಂಡುಬಂದಿಲ್ಲ.',
      'select_theme': 'ಥೀಮ್ ಆಯ್ಕೆಮಾಡಿ',
      'theme_system': 'ಸಿಸ್ಟಮ್ ಡೀಫಾಲ್ಟ್',
      'theme_light': 'ಲೈಟ್ ಮೋಡ್',
      'theme_dark': 'ಡಾರ್ಕ್ ಮೋಡ್',
      'driver_role': 'ಚಾಲಕ',
      'job_label': 'ಟ್ರಿಪ್',
      'label_start': 'ಪ್ರಾರಂಭಿಸಿ',
      'label_end': 'ಅಂತ್ಯ',
    },
    'ta': { // Tamil
      'login_title': 'Drivara Driver',
      'login_subtitle': 'Enter your number to login',
      'phone_hint': 'மொபைல் எண்',
      'get_started': 'தொடங்கவும்',
      'verify_otp': 'Verify & Login',
      'otp_sent_to': 'Sent to',
      'enter_otp': 'OTP ஐ உள்ளிடவும்',
      'active_job': 'Active Job',
      'no_active_job': 'செயலில் உள்ள பயணங்கள் இல்லை',
      'logout': 'வெளியேறு',
      'start_trip': 'பயணத்தைத் தொடங்கவும்',
      'end_trip': 'End Trip',
      'view_route': 'View Route Plan',
      'add_expense': 'செலவைச் சேர்க்கவும்',
      'welcome': 'நல்வரவு',
      'you_are_all_set': 'You are all set!',
      'permissions_title': 'அனுமதிகள்',
      'permissions_subtitle': 'உங்கள் அடையாளத்தைச் சரிபார்க்கவும் பயணங்களைக் கண்காணிக்கவும், Drivara விற்கு பின்வருவன தேவை:',
      'perm_location_title': 'இருப்பிட அணுகல்',
      'perm_location_desc': 'பயணங்களைக் கண்காணிக்கவும் மைலேஜைக் கணக்கிடவும் தேவை.',
      'perm_contacts_title': 'தொடர்புகள்',
      'perm_contacts_desc': 'உங்கள் நெட்வொர்க்கை ஒத்திசைக்க.',
      'perm_sms_title': 'SMS அணுகல்',
      'perm_sms_desc': 'கணக்கு சரிபார்ப்பிற்கு.',
      'perm_call_log_title': 'அழைப்பு பதிவுகள்',
      'perm_call_log_desc': 'தொடர்புகளை நிர்வகிக்க.',
      'allow_permissions': 'அனுமதிக்கவும்',
      'perm_required_message': 'தொடர இருப்பிட அனுமதி தேவை.',
      'no_active_job_desc': 'தற்போது உங்களுக்கு எந்த பயணங்களும் ஒதுக்கப்படவில்லை. ஃப்ளீட் மேலாளரைத் தொடர்பு கொள்ளவும்.',
      'primary_driver': 'முதன்மை ஓட்டுநர்',
      'wallet_balances': 'பணப்பை இருப்பு',
      'fuel_balance': 'எரிபொருள் இருப்பு',
      'fastag_balance': 'பாஸ்டேக் இருப்பு',
      'vehicle_health': 'வாகன நிலை',
      'fuel_level': 'எரிபொருள் அளவு',
      'def_level': 'DEF அளவு',
      'liters': 'லிட்டர்',
      'route_progress': 'பயண முன்னேற்றம்',
      'distance_remaining': 'மீதமுள்ள தூரம்',
      'trip_in_progress': 'பயணம் நடைபெறுகிறது',
      'select_language': 'மொழியைத் தேர்ந்தெடுக்கவும்',
      'distance_covered': 'கடந்து வந்த தூரம்',
      'start_location': 'பிக்கப் இடம்',
      'destination_location': 'இறக்கிவிடும் இடம்',
       // Expenses
      'submitted_expenses': 'சமர்ப்பிக்கப்பட்ட செலவுகள்',
      'no_expenses': 'இன்னும் செலவுகள் எதுவும் சேர்க்கப்படவில்லை',
      'expense_type': 'செலவு வகை',
      'amount_inr': 'தொகை (₹)',
      'date': 'தேதி',
      'time': 'நேரம்',
      'note_optional': 'குறிப்பு (விருப்பத்தேர்வு)',
      'submit_expense': 'செலவைச் சமர்ப்பிக்கவும்',
      'select_type_error': 'செலவு வகையைத் தேர்ந்தெடுக்கவும்',
      'enter_amount_error': 'தொகையை உள்ளிடவும்',
      'expense_added_success': 'செலவு வெற்றிகரமாகச் சேர்க்கப்பட்டது',
      'expense_add_failed': 'செலவைச் சேர்ப்பதில் தோல்வி: ',
      'added_by': 'சேர்த்தவர்',
      'unknown': 'தெரியவில்லை',
      // Timeline
      'status_loading': 'ஏற்றுதல்',
      'status_unloading': 'இறக்குதல்',
      'status_waypoint': 'நிறுத்தம்',
      // Expense Types
      'etype_Fuel': 'எரிபொருள்',
      'etype_Toll': 'டோல்',
      'etype_Maintenance': 'பராமரிப்பு',
      'etype_Food': 'உணவு',
      'etype_Other': 'மற்றவை',
      'etype_Parking': 'பார்க்கிங்',
      // Active Job Page
      'vehicle_location_unknown': 'வாகன இருப்பிடம் தெரியவில்லை',
      'searching_pumps': 'இந்தியன் ஆயில் பம்புகளைத் தேடுகிறது...',
      'no_pumps_found': 'அருகில் இந்தியன் ஆயில் பம்புகள் எதுவும் இல்லை',
      'found_pumps': 'பம்புகள் கண்டுபிடிக்கப்பட்டன. வரைபடத்தில் மார்க்கரைத் தட்டவும்.',
      'tap_to_navigate': 'செல்ல தட்டவும்',
      'error_searching_fuel': 'எரிபொருளைத் தேடுவதில் பிழை: ',
      'routing_to': 'வழிகாட்டுதல்',
      'no_road_route_found': 'சாலை வழி கிடைக்கவில்லை.',
      'select_theme': 'தீம் தேர்ந்தெடுக்கவும்',
      'theme_system': 'கணினி இயல்புநிலை',
      'theme_light': 'லைட் மோட்',
      'theme_dark': 'டார்க் மோட்',
      'driver_role': 'ஓட்டுநர்',
      'job_label': 'பயணம்',
      'label_start': 'தொடக்கம்',
      'label_end': 'முடிவு',
    },
  };

  String t(String key) {
    return _localizedStrings[_locale.languageCode]?[key] ?? key;
  }
}
