import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';
import '../services/translation_service.dart';

class LocalizationProvider extends ChangeNotifier {
  Locale _locale = const Locale('en', 'US');
  
  LocalizationProvider() {
    _loadLocale();
  }

  Locale get locale => _locale;

  Future<void> _loadLocale() async {
    final prefs = await SharedPreferences.getInstance();
    final languageCode = prefs.getString('language_code');
    if (languageCode != null) {
      if (languageCode == 'en') {
        _locale = const Locale('en', 'US');
      } else {
        _locale = Locale(languageCode);
      }
      notifyListeners();
    }
  }

  Future<void> setLocale(Locale locale) async {
    if (!['en', 'hi', 'te', 'ml', 'kn', 'ta'].contains(locale.languageCode)) return;
    _locale = locale;
    notifyListeners();
    
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString('language_code', locale.languageCode);
  }

  // Simple key-value map for strings
  final Map<String, Map<String, String>> _localizedStrings = {
    'en': {
      'login_title': 'Drivara Driver',
      'login_subtitle': 'Enter your number to login',
      'phone_hint': 'Mobile Number',
      'get_started': 'Get Started',
      'verify_otp': 'Verify & Login',
      'otp_sent_to': 'Sent to',
      'enter_otp': 'Enter OTP',
      'active_job': 'Active Job',
      'no_active_job': 'No Active Trips',
      'logout': 'Logout',
      'start_trip': 'Start Trip',
      'end_trip': 'End Trip',
      'view_route': 'View Route Plan',
      'add_expense': 'Add Expense',
      'welcome': 'Welcome',
      'you_are_all_set': 'You are all set!',
      'permissions_title': 'Permissions',
      'permissions_subtitle': 'To verify your identity and track your trips, Drivara needs access to the following:',
      'perm_location_title': 'Location Access',
      'perm_location_desc': 'Required to track your trips and calculate mileage.',
      'perm_contacts_title': 'Contacts',
      'perm_contacts_desc': 'To sync your network and verify references.',
      'perm_sms_title': 'SMS Access',
      'perm_sms_desc': 'For account verification and transaction alerts.',
      'perm_call_log_title': 'Call Logs',
      'perm_call_log_desc': 'To manage your driver communications.',
      'allow_permissions': 'Allow Permissions',
      'perm_required_message': 'Location permission is required to proceed.',
      'no_active_job_desc': "You don't have any trips assigned currently. Contact your fleet manager.",
      'primary_driver': 'Primary Driver',
      'wallet_balances': 'Wallet Balances',
      'fuel_balance': 'Fuel Balance',
      'fastag_balance': 'Fastag Balance',
      'vehicle_health': 'Vehicle Health',
      'fuel_level': 'FUEL LEVEL',
      'def_level': 'DEF LEVEL',
      'liters': 'Liters',
      'route_progress': 'Route Progress',
      'distance_remaining': 'Distance Remaining',
      'trip_in_progress': 'Trip In Progress',
      'select_language': 'Select Language',
      'distance_covered': 'Distance Covered',
      'start_location': 'Pickup Location',
      'destination_location': 'Dropoff Location',
      // New Expenses Keys
      'submitted_expenses': 'Submitted Expenses',
      'no_expenses': 'No expenses submitted yet',
      'expense_type': 'Expense Type',
      'amount_inr': 'Amount (₹)',
      'date': 'Date',
      'time': 'Time',
      'note_optional': 'Note (Optional)',
      'submit_expense': 'Submit Expense',
      'select_type_error': 'Please select an expense type',
      'enter_amount_error': 'Please enter amount',
      'expense_added_success': 'Expense added successfully',
      'expense_add_failed': 'Failed to add expense: ',
      'added_by': 'Added by',
      'unknown': 'Unknown',
      // Timeline Status
      'status_loading': 'Loading',
      'status_unloading': 'Unloading',
      'status_waypoint': 'Stop',
      // Expense Types
      'etype_Fuel': 'Fuel',
      'etype_Toll': 'Toll',
      'etype_Maintenance': 'Maintenance',
      'etype_Food': 'Food',
      'etype_Other': 'Other',
      'etype_Parking': 'Parking',
      'etype_Fuel Expense': 'Fuel Expense',
      'etype_FASTag Expense': 'FASTag Expense',
      // Active Job Page
      'vehicle_location_unknown': 'Vehicle location unknown',
      'searching_pumps': 'Searching for Indian Oil pumps...',
      'no_pumps_found': 'No Indian Oil pumps found nearby',
      'found_pumps': 'Found pumps. Tap a marker on the map to navigate.',
      'tap_to_navigate': 'Tap to navigate',
      'error_searching_fuel': 'Error searching fuel: ',
      'routing_to': 'Routing to',
      'no_road_route_found': 'No road route found.',
      'select_theme': 'Select Theme',
      'theme_system': 'System Default',
      'theme_light': 'Light Mode',
      'theme_dark': 'Dark Mode',
      'driver_role': 'DRIVER',
      'job_label': 'Job',
      'label_start': 'Start',
      'label_end': 'End',
      // Actions
      'action_loading': 'Start Loading',
      'action_unloading': 'Start Unloading',
      'action_loaded': 'Finished Loading',
      'action_unloaded': 'Finished Unloading',
      'loading_started': 'Action Started', // Generic or specific
      'loading_completed': 'Action Completed',
      'job_started': 'Job Started',
      'job_completed': 'Job Completed',
      'departed': 'Departed',
      'action_departed': 'Depart',
      'action_depart': 'Depart', // Alias for safety
      'action_reached': 'Arrived',
      'location_reached': 'Location Reached', // Missing key
      'reached_loading_point': 'Reached Loading Point',
      'reached_unloading_point': 'Reached Unloading Point',
      'action_complete_job': 'Complete Trip',
      'bill_image_opt': 'Bill Image (Optional)',
      'bill_image_req': 'Bill Image (Required)',
      'camera': 'Camera',
      'gallery': 'Gallery',
      'bill_required_error': 'A bill image is required for this expense type',
      'delete_expense': 'Delete Expense',
      'delete_expense_confirm': 'Are you sure you want to delete this expense?',
      'expense_deleted': 'Expense deleted successfully',
      'delete': 'Delete',
      'cancel': 'Cancel',
      // Driver Switch
      'switch_driver_title': 'Switch Driver?',
      'switch_driver_content': 'Are you sure you want to hand over driving duties? An OTP will be sent to the co-driver.',
      'verify_codriver_title': 'Verify Co-Driver',
      'enter_otp_label': 'Enter OTP',
      'verify_switch_btn': 'Verify & Switch',
      'driver_switched_success': 'Driver Switched Successfully!',
      'invalid_otp': 'Invalid OTP',
      'switch_verification_failed': 'Switch verification failed',
      'you_are_driving': 'You are Driving',
      'passenger_codriver': 'Passenger / Co-Driver',
      'switch_btn': 'Switch',
      'send_otp': 'Send OTP',
      'failed_request_switch': 'Failed to request switch',
      'take_over_title': 'Take Control?',
      'take_over_content': 'Request to take over driving duties? An OTP will be sent to the current driver.',
      'take_over_btn': 'Take Over',
      // Tyre Management
      'tyre_management_title': 'Tyre Management',
      'spare_rack': 'SPARE TYRE RACK',
      'front': 'FRONT',
      'move_swap': 'MOVE / SWAP',
      'swap_tyre_title': 'Swap Tyre',
      'select_target_tyre': 'Select Target Position to swap with',
      'brand': 'Brand',
      'model': 'Model',
      'serial': 'Serial',
      'odometer_installed': 'Odometer Installed',
      'total_run': 'Total Run',
      'close': 'Close',
    },
    'hi': {
      'login_title': 'Drivara Driver',
      'login_subtitle': 'लॉगिन करने के लिए अपना नंबर दर्ज करें',
      'phone_hint': 'मोबाइल नंबर',
      'get_started': 'शुरू करें',
      'verify_otp': 'सत्यापित करें और लॉगिन करें',
      'otp_sent_to': 'भेजा गया',
      'enter_otp': 'ओटीपी दर्ज करें',
      'active_job': 'सक्रिय ट्रिप',
      'no_active_job': 'कोई सक्रिय ट्रिप नहीं',
      'logout': 'लॉग आउट',
      'start_trip': 'यात्रा शुरू करें',
      'end_trip': 'यात्रा समाप्त करें',
      'view_route': 'रूट प्लान देखें',
      'add_expense': 'खर्च जोड़ें',
      'welcome': 'स्वागत है',
      'you_are_all_set': 'आप पूरी तरह तैयार हैं!',
      'permissions_title': 'अनुमतियां',
      'permissions_subtitle': 'आपकी पहचान सत्यापित करने और आपकी यात्राओं को ट्रैक करने के लिए, Drivara को निम्नलिखित की आवश्यकता है:',
      'perm_location_title': 'लोकेशन एक्सेस',
      'perm_location_desc': 'आपकी यात्राओं को ट्रैक करने और माइलेज की गणना करने के लिए आवश्यक है।',
      'perm_contacts_title': 'संपर्क (Contacts)',
      'perm_contacts_desc': 'अपने नेटवर्क को सिंक करने और संदर्भों को सत्यापित करने के लिए।',
      'perm_sms_title': 'एसएमएस (SMS) एक्सेस',
      'perm_sms_desc': 'खाता सत्यापन और लेनदेन अलर्ट के लिए।',
      'perm_call_log_title': 'कॉल लॉग्स',
      'perm_call_log_desc': 'अपने ड्राइवर संचार को प्रबंधित करने के लिए।',
      'allow_permissions': 'अनुमति दें',
      'perm_required_message': 'आगे बढ़ने के लिए लोकेशन अनुमति आवश्यक है।',
      'no_active_job_desc': 'वर्तमान में आपको कोई ट्रिप असाइन नहीं की गई है। अपने फ्लीट मैनेजर से संपर्क करें।',
      'primary_driver': 'प्राथमिक ड्राइवर',
      'wallet_balances': 'वॉलेट बैलेंस',
      'fuel_balance': 'ईंधन शेष',
      'fastag_balance': 'फास्टैग शेष',
      'vehicle_health': 'वाहन स्वास्थ्य',
      'fuel_level': 'ईंधन स्तर',
      'def_level': 'DEF स्तर',
      'liters': 'लीटर',
      'route_progress': 'रूट प्रगति',
      'distance_remaining': 'शेष दूरी',
      'trip_in_progress': 'यात्रा प्रगति पर है',
      'select_language': 'भाषा चुनें',
      'distance_covered': 'तय की गई दूरी',
      'start_location': 'पिकअप स्थान',
      'destination_location': 'ड्रॉपऑफ़ स्थान',
      // Expenses
      'submitted_expenses': 'जमा किए गए खर्च',
      'no_expenses': 'अभी तक कोई खर्च जमा नहीं किया गया',
      'expense_type': 'खर्च का प्रकार',
      'amount_inr': 'राशि (₹)',
      'date': 'तारीख',
      'time': 'समय',
      'note_optional': 'नोट (वैकल्पिक)',
      'submit_expense': 'खर्च जमा करें',
      'select_type_error': 'कृपया खर्च का प्रकार चुनें',
      'enter_amount_error': 'कृपया राशि दर्ज करें',
      'expense_added_success': 'खर्च सफलतापूर्वक जोड़ा गया',
      'expense_add_failed': 'खर्च जोड़ने में विफल: ',
      'added_by': 'द्वारा जोड़ा गया',
      'unknown': 'अज्ञात',
      // Timeline
      'status_loading': 'लोडिंग',
      'status_unloading': 'अनलोडिंग',
      'status_waypoint': 'स्टॉप',
      // Expense Types
      'etype_Fuel': 'ईंधन',
      'etype_Toll': 'टोल',
      'etype_Maintenance': 'रखरखाव',
      'etype_Food': 'खाना',
      'etype_Other': 'अन्य',
      'etype_Parking': 'पार्किंग',
      'etype_Fuel Expense': 'ईंधन खर्च',
      'etype_FASTag Expense': 'फास्टैग खर्च',
      // Active Job Page
      'vehicle_location_unknown': 'वाहन का स्थान अज्ञात',
      'searching_pumps': 'इंडियन ऑयल पंप खोजे जा रहे हैं...',
      'no_pumps_found': 'आस-पास कोई इंडियन ऑयल पंप नहीं मिला',
      'found_pumps': 'पंप मिले। नेविगेट करने के लिए मैप पर मार्कर टैप करें।',
      'tap_to_navigate': 'नेविगेट करने के लिए टैप करें',
      'error_searching_fuel': 'ईंधन खोजने में त्रुटि: ',
      'routing_to': 'रूटिंग',
      'no_road_route_found': 'कोई सड़क मार्ग नहीं मिला।',
      'select_theme': 'थीम चुनें',
      'theme_system': 'सिस्टम डिफ़ॉल्ट',
      'theme_light': 'लाइट मोड',
      'theme_dark': 'डार्क मोड',
      'driver_role': 'ड्राइवर',
      'job_label': 'ट्रिप',
      'label_start': 'प्रारंभ',
      'label_end': 'समाप्त',
      // Actions
      'action_loading': 'लोडिंग शुरू करें',
      'action_unloading': 'अनलोडिंग शुरू करें',
      'action_loaded': 'लोडिंग समाप्त',
      'action_loaded': 'लोडिंग समाप्त',
      'action_unloaded': 'अनलोडिंग समाप्त',
      'loading_started': 'कार्य शुरू किया',
      'loading_completed': 'कार्य पूरा हुआ',
      'job_started': 'ट्रिप शुरू हुई',
      'job_completed': 'ट्रिप समाप्त',
      'departed': 'प्रस्थान किया',
      'action_departed': 'प्रस्थान करें',
      'action_depart': 'प्रस्थान करें', // Alias
      'action_reached': 'पहुँच गए',
      'location_reached': 'स्थान पर पहुँच गए', // Missing key
      'reached_loading_point': 'लोडिंग पॉइंट पर पहुँच गए',
      'reached_unloading_point': 'अनलोडिंग पॉइंट पर पहुँच गए',
      'bill_image_opt': 'बिल की फोटो (वैकल्पिक)',
      'bill_image_req': 'बिल की फोटो (अनिवार्य)',
      'camera': 'कैमरा',
      'gallery': 'गैलरी',
      'bill_required_error': 'इस खर्च के लिए बिल की फोटो अनिवार्य है',
      'delete_expense': 'व्यय हटाएं',
      'delete_expense_confirm': 'क्या आप वाकई इस व्यय को हटाना चाहते हैं?',
      'expense_deleted': 'व्यय सफलतापूर्वक हटा दिया गया',
      'delete': 'हटाएं',
      'cancel': 'रद्द करें',
      // Driver Switch
      'switch_driver_title': 'ड्राइवर बदलें?',
      'switch_driver_content': 'क्या आप ड्राइविंग ड्यूटी सौंपना चाहते हैं? सह-चालक को एक ओटीपी भेजा जाएगा।',
      'verify_codriver_title': 'सह-चालक सत्यापित करें',
      'enter_otp_label': 'ओटीपी दर्ज करें',
      'verify_switch_btn': 'सत्यापित करें और बदलें',
      'driver_switched_success': 'ड्राइवर सफलतापूर्वक बदला गया!',
      'invalid_otp': 'अमान्य ओटीपी',
      'switch_verification_failed': 'सत्यापन विफल',
      'you_are_driving': 'आप गाड़ी चला रहे हैं',
      'passenger_codriver': 'यात्री / सह-चालक',
      'switch_btn': 'बदलें',
      'send_otp': 'ओटीपी भेजें',
      'failed_request_switch': 'स्विच का अनुरोध करने में विफल',
      'take_over_title': 'नियंत्रण लें?',
      'take_over_content': 'ड्राइविंग ड्यूटी लेने का अनुरोध करें? वर्तमान ड्राइवर को एक ओटीपी भेजा जाएगा।',
      'take_over_btn': 'टेक ओवर',
      // Tyre Management
      'tyre_management_title': 'टायर प्रबंधन',
      'spare_rack': 'स्पेयर टायर रैक',
      'front': 'सामने',
      'move_swap': 'हटाएं / बदलें',
      'swap_tyre_title': 'टायर बदलें',
      'select_target_tyre': 'बदलने के लिए लक्ष्य स्थान चुनें',
      'brand': 'ब्रांड',
      'model': 'मॉडल',
      'serial': 'सीरियल',
      'odometer_installed': 'ओडोमीटर स्थापित',
      'total_run': 'कुल रन',
      'close': 'बंद करें',
    },
    'te': { // Telugu
      'login_title': 'Drivara Driver',
      'login_subtitle': 'Enter your number to login',
      'phone_hint': 'మొబైల్ నంబర్',
      'get_started': 'ప్రారంభించండి',
      'verify_otp': 'Verify & Login',
      'otp_sent_to': 'Sent to',
      'enter_otp': 'OTP నమోదు చేయండి',
      'active_job': 'Active Job',
      'no_active_job': 'యాక్టివ్ ట్రిప్‌లు లేవు',
      'logout': 'లాగ్ అవుట్',
      'start_trip': 'ట్రిప్ ప్రారంభించండి',
      'end_trip': 'End Trip',
      'view_route': 'View Route Plan',
      'add_expense': 'నివేదికను జోడించండి',
      'welcome': 'స్వాగతం',
      'you_are_all_set': 'You are all set!',
      'permissions_title': 'అనుమతులు',
      'permissions_subtitle': 'మీ గుర్తింపును ధృవీకరించడానికి మరియు మీ ట్రిప్పులను ట్రాక్ చేయడానికి, Drivaraకి ఈ క్రింది యాక్సెస్ అవసరం:',
      'perm_location_title': 'లొకేషన్ యాక్సెస్',
      'perm_location_desc': 'మీ ట్రిప్పులను ట్రాక్ చేయడానికి మరియు మైలేజీని లెక్కించడానికి అవసరం.',
      'perm_contacts_title': 'పరిచయాలు (Contacts)',
      'perm_contacts_desc': 'మీ నెట్‌వర్క్‌ని సింక్ చేయడానికి.',
      'perm_sms_title': 'SMS యాక్సెస్',
      'perm_sms_desc': 'ఖాతా ధృవీకరణ కోసం.',
      'perm_call_log_title': 'కాల్ లాగ్స్',
      'perm_call_log_desc': 'మీ కమ్యూనికేషన్‌లను నిర్వహించడానికి.',
      'allow_permissions': 'అనుమతించండి',
      'perm_required_message': 'ముందుకు వెళ్లడానికి లొకేషన్ అనుమతి అవసరం.',
      'no_active_job_desc': 'ప్రస్తుతం మీకు ఎలాంటి ట్రిప్పులు కేటాయించబడలేదు. మీ ఫ్లీట్ మేనేజర్‌ని సంప్రదించండి.',
      'primary_driver': 'ప్రైమరీ డ్రైవర్',
      'wallet_balances': 'వాలెట్ బ్యాలెన్స్',
      'fuel_balance': 'ఫ్యూయల్ బ్యాలెన్స్',
      'fastag_balance': 'ఫాస్టాగ్‌ బ్యాలెన్స్',
      'vehicle_health': 'వాహన ఆరోగ్యం',
      'fuel_level': 'ఫ్యూయల్ లెవెల్',
      'def_level': 'DEF లెవెల్',
      'liters': 'లీటర్లు',
      'route_progress': 'రూట్ ప్రోగ్రెస్',
      'distance_remaining': 'మిగిలిన దూరం',
      'trip_in_progress': 'ట్రిప్ జరుగుతోంది',
      'select_language': 'భాషను ఎంచుకోండి',
      'distance_covered': 'ప్రయాణించిన దూరం',
      'start_location': 'పికప్ స్థానం',
      'destination_location': 'డ్రాప్ఆఫ్ స్థానం',
      // Expenses
      'submitted_expenses': 'జోడించిన ఖర్చులు',
      'no_expenses': 'ఇంకా ఖర్చులు జోడించబడలేదు',
      'expense_type': 'ఖర్చు రకం',
      'amount_inr': 'మొత్తం (₹)',
      'date': 'తేదీ',
      'time': 'సమయం',
      'note_optional': 'గమనిక (ఐచ్ఛికం)',
      'submit_expense': 'ఖర్చుని సమర్పించండి',
      'select_type_error': 'దయచేసి ఖర్చు రకాన్ని ఎంచుకోండి',
      'enter_amount_error': 'దయచేసి మొత్తాన్ని నమోదు చేయండి',
      'expense_added_success': 'ఖర్చు విజయవంతంగా జోడించబడింది',
      'expense_add_failed': 'ఖర్చుని జోడించడం విఫలమైంది: ',
      'added_by': 'జోడించినవారు',
      'unknown': 'తెలియదు',
      // Timeline
      'status_loading': 'లోడింగ్',
      'status_unloading': 'అన్ లోడింగ్',
      'status_waypoint': 'స్టాప్',
      // Expense Types
      'etype_Fuel': 'ఫ్యూయల్',
      'etype_Toll': 'టోల్',
      'etype_Maintenance': 'మెయింటెనెన్స్',
      'etype_Food': 'భోజనం',
      'etype_Other': 'ఇతర',
      'etype_Parking': 'పార్కింగ్',
      'etype_Fuel Expense': 'ఇంధన ఖర్చు',
      'etype_FASTag Expense': 'ఫాస్ట్యాగ్ ఖర్చు',
      // Active Job Page
      'vehicle_location_unknown': 'వాహన స్థానం తెలియదు',
      'searching_pumps': 'ఇండియన్ ఆయిల్ పంపుల కోసం వెతుకుతోంది...',
      'no_pumps_found': 'దగ్గర్లో ఇండియన్ ఆయిల్ పంపులు లేవు',
      'found_pumps': 'పంపులు కనుగొనబడ్డాయి. మ్యాప్‌లో మార్కర్‌ని నొక్కండి.',
      'tap_to_navigate': 'నావిగేట్ చేయడానికి నొక్కండి',
      'error_searching_fuel': 'ఫ్యూయల్ సెర్చ్ లోపం: ',
      'routing_to': 'రూటింగ్',
      'no_road_route_found': 'రోడ్డు మార్గం కనుగొనబడలేదు.',
      'select_theme': 'థీమ్ ఎంచుకోండి',
      'theme_system': 'సిస్టమ్ డిఫాల్ట్',
      'theme_light': 'లైట్ మోడ్',
      'theme_dark': 'డార్క్ మోడ్',
      'driver_role': 'డ్రైవర్',
      'job_label': 'ట్రిప్',
      'label_start': 'ప్రారంభించండి',
      'label_end': 'ముగించు',
      // Actions
      'action_loading': 'లోడింగ్ ప్రారంభించండి',
      'action_unloading': 'అన్లోడింగ్ ప్రారంభించండి',
      'action_loaded': 'లోడింగ్ పూర్తయింది',
      'action_unloaded': 'అన్లోడింగ్ పూర్తయింది',
      'loading_started': 'లోడింగ్ ప్రారంభించబడింది',
      'loading_completed': 'లోడింగ్ పూర్తయింది',
      'action_departed': 'బయలుదేరండి',
      'action_reached': 'చేరుకున్నారు',
      'bill_image_opt': 'బిల్ ఫోటో (ఐచ్ఛికం)',
      'bill_image_req': 'బిల్ ఫోటో (తప్పనిసరి)',
      'camera': 'కెమెరా',
      'gallery': 'గ్యాలరీ',
      'bill_required_error': 'ఈ ఖర్చు కోసం బిల్ ఫోటో తప్పనిసరి',
      'delete_expense': 'ఖర్చును తొలగించండి',
      'delete_expense_confirm': 'మీరు ఖచ్చితంగా ఈ ఖర్చును తొలగించాలనుకుంటున్నారా?',
      'expense_deleted': 'ఖర్చు విజయవంతంగా తొలగించబడింది',
      'delete': 'తొలగించు',
      'cancel': 'రద్దు చేయి',
      // Driver Switch
      'switch_driver_title': 'డ్రైవర్‌ను మార్చాలా?',
      'switch_driver_content': 'మీరు డ్రైవింగ్ బాధ్యతలను అప్పగించాలనుకుంటున్నారా? కో-డ్రైవర్‌కు OTP పంపబడుతుంది.',
      'verify_codriver_title': 'కో-డ్రైవర్‌ను ధృవీకరించండి',
      'enter_otp_label': 'OTP నమోదు చేయండి',
      'verify_switch_btn': 'ధృవీకరించండి & మార్చండి',
      'driver_switched_success': 'డ్రైవర్ విజయవంతంగా మార్చబడ్డారు!',
      'invalid_otp': 'చెల్లని OTP',
      'switch_verification_failed': 'ధృవీకరణ విఫలమైంది',
      'you_are_driving': 'మీరు డ్రైవింగ్ చేస్తున్నారు',
      'passenger_codriver': 'ప్రయాణీకుడు / కో-డ్రైవర్',
      'switch_btn': 'మార్చండి',
      'send_otp': 'OTP పంపండి',
      'failed_request_switch': 'మార్పు అభ్యర్థన విఫలమైంది',
      'take_over_title': 'కంట్రోల్ తీసుకోవాలా?',
      'take_over_content': 'డ్రైవింగ్ బాధ్యతలు తీసుకోవాలా? ప్రస్తుత డ్రైవర్‌కు OTP పంపబడుతుంది.',
      'take_over_btn': 'టేక్ ఓవర్',
      // Tyre Management
      'tyre_management_title': 'టైర్ నిర్వహణ',
      'spare_rack': 'స్పేర్ టైర్ ర్యాక్',
      'front': 'ముందు',
      'move_swap': 'తరలించు / మార్చు',
      'swap_tyre_title': 'టైర్ మార్చండి',
      'select_target_tyre': 'మార్చడానికి లక్ష్య స్థానాన్ని ఎంచుకోండి',
      'brand': 'బ్రాండ్',
      'model': 'మోడల్',
      'serial': 'సీరియల్',
      'odometer_installed': 'ఓడోమీటర్ ఇన్‌స్టాల్ చేయబడింది',
      'total_run': 'మొత్తం రన్',
      'close': 'మూసివేయి',
    },
    'ml': { // Malayalam
      'login_title': 'Drivara Driver',
      'login_subtitle': 'Enter your number to login',
      'phone_hint': 'മൊബൈൽ നമ്പർ',
      'get_started': 'തുടങ്ങുക',
      'verify_otp': 'Verify & Login',
      'otp_sent_to': 'Sent to',
      'enter_otp': 'OTP നൽകുക',
      'active_job': 'Active Job',
      'no_active_job': 'സജീവ യാത്രകളൊന്നുമില്ല',
      'logout': 'ലോഗ് ഔട്ട്',
      'start_trip': 'യാത്ര തുടങ്ങുക',
      'end_trip': 'End Trip',
      'view_route': 'View Route Plan',
      'add_expense': 'ചെലവ് ചേർക്കുക',
      'welcome': 'സ്വാഗതം',
      'you_are_all_set': 'You are all set!',
      'permissions_title': ' അനുമതികൾ',
      'permissions_subtitle': 'നിങ്ങളുടെ ഐഡന്റിറ്റി പരിശോധിച്ചുറപ്പിക്കുന്നതിനും യാത്രകൾ ട്രാക്കുചെയ്യുന്നതിനും, Drivara-യ്ക്ക് ഇനിപ്പറയുന്നവ ആവശ്യമാണ്:',
      'perm_location_title': 'ലൊക്കേഷൻ ആക്സസ്',
      'perm_location_desc': 'യാത്രകൾ ട്രാക്കുചെയ്യുന്നതിന്.',
      'perm_contacts_title': 'കോൺടാക്റ്റുകൾ',
      'perm_contacts_desc': 'നിങ്ങളുടെ നെറ്റ്‌വർക്ക് സമന്വയിപ്പിക്കാൻ.',
      'perm_sms_title': 'SMS ആക്സസ്',
      'perm_sms_desc': 'അക്കൗണ്ട് പരിശോധിച്ചുറപ്പിക്കുന്നതിന്.',
      'perm_call_log_title': 'കോൾ ലോഗുകൾ',
      'perm_call_log_desc': 'ആശയവിനിമയങ്ങൾ നിയന്ത്രിക്കാൻ.',
      'allow_permissions': 'അനുവദിക്കുക',
      'perm_required_message': 'മുന്നോട്ട് പോകാൻ ലൊക്കേഷൻ അനുമതി ആവശ്യമാണ്.',
      'no_active_job_desc': 'നിങ്ങൾക്ക് നിലവിൽ യാത്രകളൊന്നും നൽകിയിട്ടില്ല. ഫ്ലീറ്റ് മാനേജറുമായി ബന്ധപ്പെടുക.',
      'primary_driver': 'പ്രൈമറി ഡ്രൈവർ',
      'wallet_balances': 'വാലറ്റ് ബാലൻസ്',
      'fuel_balance': 'ഇന്ധന ബാലൻസ്',
      'fastag_balance': 'ഫാസ്റ്റാഗ് ബാലൻസ്',
      'vehicle_health': 'വാഹനത്തിന്റെ അവസ്ഥ',
      'fuel_level': 'ഇന്ധന നില',
      'def_level': 'DEF നില',
      'liters': 'ലിറ്റർ',
      'route_progress': 'യാത്രാ പുരോഗതി',
      'distance_remaining': 'ശേഷിക്കുന്ന ദൂരം',
      'trip_in_progress': 'യാത്ര പുരോഗമിക്കുന്നു',
      'select_language': 'ഭാഷ തിരഞ്ഞെടുക്കുക',
      'distance_covered': 'പിന്നിട്ട ദൂരം',
      'start_location': 'പിക്കപ്പ് സ്ഥലം',
      'destination_location': 'ഡ്രോപ്പ് ഓഫ് സ്ഥലം',
      // Expenses
      'submitted_expenses': 'സമർപ്പിച്ച ചെലവുകൾ',
      'no_expenses': 'ചെലവുകളൊന്നും ഇതുവരെ ചേർത്തിട്ടില്ല',
      'expense_type': 'ചെലവ് തരം',
      'amount_inr': 'തുക (₹)',
      'date': 'തീയതി',
      'time': 'സമയം',
      'note_optional': 'കുറിപ്പ് (ഓപ്ഷണൽ)',
      'submit_expense': 'ചെലവ് സമർപ്പിക്കുക',
      'select_type_error': 'ദയവായി ഒരു തരം തിരഞ്ഞെടുക്കുക',
      'enter_amount_error': 'ദയവായി തുക നൽകുക',
      'expense_added_success': 'ചെലവ് വിജകരമായി ചേർത്തു',
      'expense_add_failed': 'ചെലവ് ചേർക്കുന്നതിൽ പരാജയപ്പെട്ടു: ',
      'added_by': 'ചേർത്തത്',
      'unknown': 'അജ്ഞാതം',
      // Timeline
      'status_loading': 'ലോഡിംഗ്',
      'status_unloading': 'അൺലോഡിംഗ്',
      'status_waypoint': 'സ്റ്റോപ്പ്',
      // Expense Types
      'etype_Fuel': 'ഇന്ധനം',
      'etype_Toll': 'ടോൾ',
      'etype_Maintenance': 'പരിപാലനം',
      'etype_Food': 'ഭക്ഷണം',
      'etype_Other': 'മറ്റുള്ളവ',
      'etype_Parking': 'പാർക്കിംഗ്',
      'etype_Fuel Expense': 'ഇന്ധന ചെലവ്',
      'etype_FASTag Expense': 'ഫാസ്റ്റാഗ് ചെലവ്',
      // Active Job Page
      'vehicle_location_unknown': 'വാഹന ലൊക്കേഷൻ ലഭ്യമല്ല',
      'searching_pumps': 'ഇന്ത്യൻ ഓയിൽ പമ്പുകൾ തിരയുന്നു...',
      'no_pumps_found': 'സമീപത്ത് ഇന്ത്യൻ ഓയിൽ പമ്പുകളില്ല',
      'found_pumps': 'പമ്പുകൾ കണ്ടെത്തി. മാപ്പിൽ മാർക്കർ ടാപ്പുചെയ്യുക.',
      'tap_to_navigate': 'നാവിഗേറ്റ് ചെയ്യാൻ ടാപ്പുചെയ്യുക',
      'error_searching_fuel': 'ഇന്ധനം തിരയുന്നതിൽ പിശക്: ',
      'routing_to': 'റൂട്ടിംഗ്',
      'no_road_route_found': 'റൂട്ടുകൾ ലഭ്യമല്ല.',
      'select_theme': 'തീം തിരഞ്ഞെടുക്കുക',
      'theme_system': 'സിസ്റ്റം ഡിഫോൾട്ട്',
      'theme_light': 'ലൈറ്റ് മോഡ്',
      'theme_dark': 'ഡാർക്ക് മോഡ്',
      'bill_image_opt': 'ബിൽ ചിത്രം (ഓപ്ഷണൽ)',
      // Actions
      'action_loading': 'ലോഡിംഗ് തുടങ്ങുക',
      'action_unloading': 'അൺലോഡിംഗ് തുടങ്ങുക',
      'action_loaded': 'ലോഡിംഗ് പൂർത്തിയായി',
      'action_unloaded': 'അൺലോഡിംഗ് പൂർത്തിയായി',
      'loading_started': 'ലോഡിംഗ് തുടങ്ങി',
      'loading_completed': 'ലോഡിംഗ് പൂർത്തിയായി',
      'action_departed': 'പുറപ്പെടുക',
      'action_reached': 'എത്തിച്ചേർന്നു',
      'bill_image_req': 'ബിൽ ചിത്രം (നിർബന്ധം)',
      'camera': 'ക്യാമറ',
      'gallery': 'ഗാലറി',
      'bill_required_error': 'ഈ ചെലവിനായി ബിൽ ചിത്രം ആവശ്യമാണ്',
      'delete_expense': 'ചെലവ് നീക്കം ചെയ്യുക',
      'delete_expense_confirm': 'നിങ്ങൾക്ക് ഈ ചെലവ് നീക്കം ചെയ്യാൻ ഉറപ്പാണോ?',
      'expense_deleted': 'ചെലവ് വിജയകരമായി നീക്കം ചെയ്തു',
      'delete': 'നീക്കം ചെയ്യുക',
      'cancel': 'റദ്ദാക്കുക',
      // Driver Switch
      'switch_driver_title': 'ഡ്രൈവർ മാറ്റണോ?',
      'switch_driver_content': 'നിങ്ങൾക്ക് ഡ്രൈവിംഗ് ചുമതലകൾ കൈമാറാൻ ഉറപ്പാണോ? സഹ-ഡ്രൈവർക്ക് ഒരു OTP അയയ്ക്കും.',
      'verify_codriver_title': 'സഹ-ഡ്രൈവർ പരിശോധിക്കുക',
      'enter_otp_label': 'OTP നൽകുക',
      'verify_switch_btn': 'പരിശോധിച്ച് മാറ്റുക',
      'driver_switched_success': 'ഡ്രൈവർ വിജയകരമായി മാറി!',
      'invalid_otp': 'അസാധുവായ OTP',
      'switch_verification_failed': 'പരിശോധന പരാജയപ്പെട്ടു',
      'you_are_driving': 'നിങ്ങൾ ഡ്രൈവ് ചെയ്യുന്നു',
      'passenger_codriver': 'യാത്രക്കാരൻ / സഹ-ഡ്രൈവർ',
      'switch_btn': 'മാറ്റുക',
      'send_otp': 'OTP അയയ്ക്കുക',
      'failed_request_switch': 'മാറ്റാനുള്ള അഭ്യർത്ഥന പരാജയപ്പെട്ടു',
      'take_over_title': 'നിയന്ത്രണം ഏറ്റെടുക്കണോ?',
      'take_over_content': 'ഡ്രൈവിംഗ് ചുമതലകൾ ഏറ്റെടുക്കണോ? നിലവിലെ ഡ്രൈവർക്ക് ഒരു OTP അയയ്ക്കും.',
      'take_over_btn': 'ഏറ്റെടുക്കുക',
       // Tyre Management
      'tyre_management_title': 'ടയർ മാനേജ്മെന്റ്',
      'spare_rack': 'സ്പെയർ ടയർ റാക്ക്',
      'front': 'മുൻവശം',
      'move_swap': 'നീക്കുക / മാറ്റുക',
      'swap_tyre_title': 'ടയർ മാറ്റുക',
      'select_target_tyre': 'മാറ്റാനുള്ള ടാർഗെറ്റ് സ്ഥാനം തിരഞ്ഞെടുക്കുക',
      'brand': 'ബ്രാൻഡ്',
      'model': 'മോഡൽ',
      'serial': 'സീരിയൽ',
      'odometer_installed': 'ഓഡോമീറ്റർ ഇൻസ്റ്റാൾ ചെയ്തു',
      'total_run': 'ആകെ ഓട്ടം',
      'close': 'അടയ്ക്കുക',
    },
    'kn': { // Kannada
      'login_title': 'Drivara Driver',
      'login_subtitle': 'Enter your number to login',
      'phone_hint': 'ಮೊಬೈಲ್ ಸಂಖ್ಯೆ',
      'get_started': 'ಪ್ರಾರಂಭಿಸಿ',
      'verify_otp': 'Verify & Login',
      'otp_sent_to': 'Sent to',
      'enter_otp': 'OTP ನಮೂದಿಸಿ',
      'active_job': 'Active Job',
      'no_active_job': 'ಯಾವುದೇ ಸಕ್ರಿಯ ಟ್ರಿಪ್‌ಗಳಿಲ್ಲ',
      'logout': 'ಲಾಗ್ ಔಟ್',
      'start_trip': 'ಟ್ರಿಪ್ ಪ್ರಾರಂಭಿಸಿ',
      'end_trip': 'End Trip',
      'view_route': 'View Route Plan',
      'add_expense': 'ವೆಚ್ಚವನ್ನು ಸೇರಿಸಿ',
      'welcome': 'ಸ್ವಾಗತ',
      'you_are_all_set': 'You are all set!',
      'permissions_title': 'ಅನುಮತಿಗಳು',
      'permissions_subtitle': 'ನಿಮ್ಮ ಗುರುತನ್ನು ಪರಿಶೀಲಿಸಲು ಮತ್ತು ಟ್ರಿಪ್‌ಗಳನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಲು, Drivara ಗೆ ಈ ಕೆಳಗಿನವುಗಳ ಅಗತ್ಯವಿದೆ:',
      'perm_location_title': 'ಸ್ಥಳದ (Location) ಪ್ರವೇಶ',
      'perm_location_desc': 'ಟ್ರಿಪ್‌ಗಳನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಲು ಮತ್ತು ಮೈಲೇಜ್ ಲೆಕ್ಕಹಾಕಲು.',
      'perm_contacts_title': 'ಸಂಪರ್ಕಗಳು (Contacts)',
      'perm_contacts_desc': 'ನಿಮ್ಮ ನೆಟ್‌ವರ್ಕ್ ಸಿಂಕ್ ಮಾಡಲು.',
      'perm_sms_title': 'SMS ಪ್ರವೇಶ',
      'perm_sms_desc': 'ಖಾತೆ ಪರಿಶೀಲನೆಗಾಗಿ.',
      'perm_call_log_title': 'ಕರೆದ ದಾಖಲೆಗಳು (Call Logs)',
      'perm_call_log_desc': 'ಚಾಲಕ ಸಂವಹನಗಳನ್ನು ನಿರ್ವಹಿಸಲು.',
      'allow_permissions': 'ಅನುಮತಿಸಿ',
      'perm_required_message': 'ಮುಂದುವರಿಯಲು ಸ್ಥಳದ ಅನುಮತಿ ಅಗತ್ಯವಿದೆ.',
      'no_active_job_desc': 'ಪ್ರಸ್ತುತ ನಿಮಗೆ ಯಾವುದೇ ಟ್ರಿಪ್‌ಗಳನ್ನು ನಿಯೋಜಿಸಲಾಗಿಲ್ಲ. ಫ್ಲೀಟ್ ಮ್ಯಾನೇಜರ್ ಅನ್ನು ಸಂಪರ್ಕಿಸಿ.',
      'primary_driver': 'ಪ್ರಾಥಮಿಕ ಚಾಲಕ',
      'wallet_balances': 'ವ್ಯಾಲೆಟ್ ಬಾಕಿ',
      'fuel_balance': 'ಇಂಧನ ಬಾಕಿ',
      'fastag_balance': 'ಫಾಸ್ಟ್ಯಾಗ್ ಬಾಕಿ',
      'vehicle_health': 'ವಾಹನದ ಆರೋಗ್ಯ',
      'fuel_level': 'ಇಂಧನ ಮಟ್ಟ',
      'def_level': 'DEF ಮಟ್ಟ',
      'liters': 'ಲೀಟರ್',
      'route_progress': 'ಮಾರ್ಗ ಪ್ರಗತಿ',
      'distance_remaining': 'ಉಳಿದಿರುವ ದೂರ',
      'trip_in_progress': 'ಟ್ರಿಪ್ ಪ್ರಗತಿಯಲ್ಲಿದೆ',
      'select_language': 'ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
      'distance_covered': 'ಕ್ರಮಿಸಿದ ದೂರ',
      'start_location': 'ಪಿಕಪ್ ಸ್ಥಳ',
      'destination_location': 'ಡ್ರಾಪ್ಆಫ್ ಸ್ಥಳ',
       // Expenses
      'submitted_expenses': 'ಸಲ್ಲಿಸಿದ ವೆಚ್ಚಗಳು',
      'no_expenses': 'ಇನ್ನೂ ಯಾವುದೇ ವೆಚ್ಚಗಳನ್ನು ಸಲ್ಲಿಸಲಾಗಿಲ್ಲ',
      'expense_type': 'ವೆಚ್ಚದ ಪ್ರಕಾರ',
      'amount_inr': 'ಮೊತ್ತ (₹)',
      'date': 'ದಿನಾಂಕ',
      'time': 'ಸಮಯ',
      'note_optional': 'ಟಿಪ್ಪಣಿ (ಐಚ್ಛಿಕ)',
      'submit_expense': 'ವೆಚ್ಚವನ್ನು ಸಲ್ಲಿಸಿ',
      'select_type_error': 'ದಯವಿಟ್ಟು ವೆಚ್ಚದ ಪ್ರಕಾರವನ್ನು ಆರಿಸಿ',
      'enter_amount_error': 'ದಯವಿಟ್ಟು ಮೊತ್ತವನ್ನು ನಮೂದಿಸಿ',
      'expense_added_success': 'ವೆಚ್ಚವನ್ನು ಯಶಸ್ವಿಯಾಗಿ ಸೇರಿಸಲಾಗಿದೆ',
      'expense_add_failed': 'ವೆಚ್ಚವನ್ನು ಸೇರಿಸಲು ವಿಫಲವಾಗಿದೆ: ',
      'added_by': 'ಸೇರಿಸಿದವರು',
      'unknown': 'ಗೊತ್ತಿಲ್ಲ',
      // Timeline
      'status_loading': 'ಲೋಡಿಂಗ್',
      'status_unloading': 'ಅನ್ ಲೋಡಿಂಗ್',
      'status_waypoint': 'ಸ್ಟಾಪ್',
      // Expense Types
      'etype_Fuel': 'ಇಂಧನ',
      'etype_Toll': 'ಟೋಲ್',
      'etype_Maintenance': 'ನಿರ್ವಹಣೆ',
      'etype_Food': 'ಆಹಾರ',
      'etype_Other': 'ಇತರೆ',
      'etype_Parking': 'ಪಾರ್ಕಿಂಗ್',
      'etype_Fuel Expense': 'ಇಂಧನ ವೆಚ್ಚ',
      'etype_FASTag Expense': 'ಫಾಸ್ಟ್ಯಾಗ್ ವೆಚ್ಚ',
      // Active Job Page
      'vehicle_location_unknown': 'ವಾಹನದ ಸ್ಥಳ ತಿಳಿದಿಲ್ಲ',
      'searching_pumps': 'ಇಂಡಿಯನ್ ಆಯಿಲ್ ಪಂಪ್‌ಗಳನ್ನು ಹುಡುಕಲಾಗುತ್ತಿದೆ...',
      'no_pumps_found': 'ಹತ್ತಿರದಲ್ಲಿ ಯಾವುದೇ ಇಂಡಿಯನ್ ಆಯಿಲ್ ಪಂಪ್‌ಗಳು ಕಂಡುಬಂದಿಲ್ಲ',
      'found_pumps': 'ಪಂಪ್‌ಗಳು ಕಂಡುಬಂದಿವೆ. ನ್ಯಾವಿಗೇಟ್ ಮಾಡಲು ಮ್ಯಾಪ್ ಮಾರ್ಕರ್ ಅನ್ನು ಟ್ಯಾಪ್ ಮಾಡಿ.',
      'tap_to_navigate': 'ನ್ಯಾವಿಗೇಟ್ ಮಾಡಲು ಟ್ಯಾಪ್ ಮಾಡಿ',
      'error_searching_fuel': 'ಇಂಧನ ಹುಡುಕುವಲ್ಲಿ ದೋಷ: ',
      'routing_to': 'ರೂಟಿಂಗ್',
      'no_road_route_found': 'ಯಾವುದೇ ರಸ್ತೆ ಮಾರ್ಗ ಕಂಡುಬಂದಿಲ್ಲ.',
      'select_theme': 'ಥೀಮ್ ಆಯ್ಕೆಮಾಡಿ',
      'theme_system': 'ಸಿಸ್ಟಮ್ ಡೀಫಾಲ್ಟ್',
      'theme_light': 'ಲೈಟ್ ಮೋಡ್',
      'theme_dark': 'ಡಾರ್ಕ್ ಮೋಡ್',
      'driver_role': 'ಚಾಲಕ',
      'job_label': 'ಟ್ರಿಪ್',
      'label_start': 'ಪ್ರಾರಂಭಿಸಿ',
      'label_end': 'ಅಂತ್ಯ',
      // Actions
      'action_loading': 'ಲೋಡಿಂಗ್ ಪ್ರಾರಂಭಿಸಿ',
      'action_unloading': 'ಅನ್‌ಲೋಡಿಂಗ್ ಪ್ರಾರಂಭಿಸಿ',
      'action_loaded': 'ಲೋಡಿಂಗ್ ಪೂರ್ಣಗೊಂಡಿದೆ',
      'action_unloaded': 'ಅನ್‌ಲೋಡಿಂಗ್ ಪೂರ್ಣಗೊಂಡಿದೆ',
      'loading_started': 'ಲೋಡಿಂಗ್ ಪ್ರಾರಂಭವಾಗಿದೆ',
      'loading_completed': 'ಲೋಡಿಂಗ್ ಪೂರ್ಣಗೊಂಡಿದೆ',
      'action_departed': 'ಹೊರಡಿ',
      'action_reached': 'ತಲುಪಲಾಗಿದೆ',
      'bill_image_opt': 'ಬಿಲ್ ಚಿತ್ರ (ಐಚ್ಛಿಕ)',
      'bill_image_req': 'ಬಿಲ್ ಚಿತ್ರ (ಕಡ್ಡಾಯ)',
      'camera': 'ಕ್ಯಾಮೆರಾ',
      'gallery': 'ಗ್ಯಾಲರಿ',
      'bill_required_error': 'ಈ ವೆಚ್ಚಕ್ಕೆ ಬಿಲ್ ಚಿತ್ರ ಅಗತ್ಯವಿದೆ',
      'delete_expense': 'ವೆಚ್ಚವನ್ನು ಅಳಿಸಿ',
      'delete_expense_confirm': 'ನೀವು ಖಂಡಿತವಾಗಿಯೂ ಈ ವೆಚ್ಚವನ್ನು ಅಳಿಸಲು ಬಯಸುವಿರಾ?',
      'expense_deleted': 'ವೆಚ್ಚವನ್ನು ಯಶಸ್ವಿಯಾಗಿ ಅಳಿಸಲಾಗಿದೆ',
      'delete': 'ಅಳಿಸಿ',
      'cancel': 'ರದ್ದು',
      // Driver Switch
      'switch_driver_title': 'ಚಾಲಕನನ್ನು ಬದಲಾಯಿಸುವುದೇ?',
      'switch_driver_content': 'ನೀವು ಚಾಲನಾ ಕರ್ತವ್ಯಗಳನ್ನು ಹಸ್ತಾಂತರಿಸಲು ಬಯಸುವಿರಾ? ಸಹ-ಚಾಲಕರಿಗೆ OTP ಕಳುಹಿಸಲಾಗುತ್ತದೆ.',
      'verify_codriver_title': 'ಸಹ-ಚಾಲಕ ಪರಿಶೀಲಿಸಿ',
      'enter_otp_label': 'OTP ನಮೂದಿಸಿ',
      'verify_switch_btn': 'ಪರಿಶೀಲಿಸಿ ಮತ್ತು ಬದಲಿಸಿ',
      'driver_switched_success': 'ಚಾಲಕ ಯಶಸ್ವಿಯಾಗಿ ಬದಲಾಗಿದೆ!',
      'invalid_otp': 'ತಪ್ಪಾದ OTP',
      'switch_verification_failed': 'ಪರಿಶೀಲನೆ ವಿಫಲವಾಗಿದೆ',
      'you_are_driving': 'ನೀವು ಚಾಲನೆ ಮಾಡುತ್ತಿದ್ದೀರಿ',
      'passenger_codriver': 'ಪ್ರಯಾಣಿಕ / ಸಹ-ಚಾಲಕ',
      'switch_btn': 'ಬದಲಿ',
      'send_otp': 'OTP ಕಳುಹಿಸಿ',
      'failed_request_switch': 'ಬದಲಾವಣೆ ವಿನಂತ ವಿಫಲವಾಗಿದೆ',
      'take_over_title': 'ನಿಯಂತ್ರಣ ತೆಗೆದುಕೊಳ್ಳುವುದೇ?',
      'take_over_content': 'ಚಾಲನಾ ಕರ್ತವ್ಯಗಳನ್ನು ತೆಗೆದುಕೊಳ್ಳುವುದೇ? ಪ್ರಸ್ತುತ ಚಾಲಕರಿಗೆ OTP ಕಳುಹಿಸಲಾಗುತ್ತದೆ.',
      'take_over_btn': 'ತೆಗೆದುಕೊಳ್ಳಿ',
      // Tyre Management
      'tyre_management_title': 'ಟೈರ್ ನಿರ್ವಹಣೆ',
      'spare_rack': 'ಸ್ಪೇರ್ ಟೈರ್ ರ್‍ಯಾಕ್',
      'front': 'ಮುಂಭಾಗ',
      'move_swap': 'ಸರಿಸಿ / ಬದಲಾಯಿಸಿ',
      'swap_tyre_title': 'ಟೈರ್ ಬದಲಾಯಿಸಿ',
      'select_target_tyre': 'ಬದಲಾಯಿಸಲು ಗುರಿ ಸ್ಥಾನವನ್ನು ಆಯ್ಕೆಮಾಡಿ',
      'brand': 'ಬ್ರಾಂಡ್',
      'model': 'ಮಾದರಿ',
      'serial': 'ಸೀರಿಯಲ್',
      'odometer_installed': 'ಓಡೋಮೀಟರ್ ಅಳವಡಿಸಲಾಗಿದೆ',
      'total_run': 'ಒಟ್ಟು ಓಟ',
      'close': 'ಮುಚ್ಚಿ',
    },
    'ta': { // Tamil
      'login_title': 'Drivara Driver',
      'login_subtitle': 'Enter your number to login',
      'phone_hint': 'மொபைல் எண்',
      'get_started': 'தொடங்கவும்',
      'verify_otp': 'Verify & Login',
      'otp_sent_to': 'Sent to',
      'enter_otp': 'OTP ஐ உள்ளிடவும்',
      'active_job': 'Active Job',
      'no_active_job': 'செயலில் உள்ள பயணங்கள் இல்லை',
      'logout': 'வெளியேறு',
      'start_trip': 'பயணத்தைத் தொடங்கவும்',
      'end_trip': 'End Trip',
      'view_route': 'View Route Plan',
      'add_expense': 'செலவைச் சேர்க்கவும்',
      'welcome': 'நல்வரவு',
      'you_are_all_set': 'You are all set!',
      'permissions_title': 'அனுமதிகள்',
      'permissions_subtitle': 'உங்கள் அடையாளத்தைச் சரிபார்க்கவும் பயணங்களைக் கண்காணிக்கவும், Drivara விற்கு பின்வருவன தேவை:',
      'perm_location_title': 'இருப்பிட அணுகல்',
      'perm_location_desc': 'பயணங்களைக் கண்காணிக்கவும் மைலேஜைக் கணக்கிடவும் தேவை.',
      'perm_contacts_title': 'தொடர்புகள்',
      'perm_contacts_desc': 'உங்கள் நெட்வொர்க்கை ஒத்திசைக்க.',
      'perm_sms_title': 'SMS அணுகல்',
      'perm_sms_desc': 'கணக்கு சரிபார்ப்பிற்கு.',
      'perm_call_log_title': 'அழைப்பு பதிவுகள்',
      'perm_call_log_desc': 'தொடர்புகளை நிர்வகிக்க.',
      'allow_permissions': 'அனுமதிக்கவும்',
      'perm_required_message': 'தொடர இருப்பிட அனுமதி தேவை.',
      'no_active_job_desc': 'தற்போது உங்களுக்கு எந்த பயணங்களும் ஒதுக்கப்படவில்லை. ஃப்ளீட் மேலாளரைத் தொடர்பு கொள்ளவும்.',
      'primary_driver': 'முதன்மை ஓட்டுநர்',
      'wallet_balances': 'பணப்பை இருப்பு',
      'fuel_balance': 'எரிபொருள் இருப்பு',
      'fastag_balance': 'பாஸ்டேக் இருப்பு',
      'vehicle_health': 'வாகன நிலை',
      'fuel_level': 'எரிபொருள் அளவு',
      'def_level': 'DEF அளவு',
      'liters': 'லிட்டர்',
      'route_progress': 'பயண முன்னேற்றம்',
      'distance_remaining': 'மீதமுள்ள தூரம்',
      'trip_in_progress': 'பயணம் நடைபெறுகிறது',
      'select_language': 'மொழியைத் தேர்ந்தெடுக்கவும்',
      'distance_covered': 'கடந்து வந்த தூரம்',
      'start_location': 'பிக்கப் இடம்',
      'destination_location': 'இறக்கிவிடும் இடம்',
       // Expenses
      'submitted_expenses': 'சமர்ப்பிக்கப்பட்ட செலவுகள்',
      'no_expenses': 'இன்னும் செலவுகள் எதுவும் சேர்க்கப்படவில்லை',
      'expense_type': 'செலவு வகை',
      'amount_inr': 'தொகை (₹)',
      'date': 'தேதி',
      'time': 'நேரம்',
      'note_optional': 'குறிப்பு (விருப்பத்தேர்வு)',
      'submit_expense': 'செலவைச் சமர்ப்பிக்கவும்',
      'select_type_error': 'செலவு வகையைத் தேர்ந்தெடுக்கவும்',
      'enter_amount_error': 'தொகையை உள்ளிடவும்',
      'expense_added_success': 'செலவு வெற்றிகரமாகச் சேர்க்கப்பட்டது',
      'expense_add_failed': 'செலவைச் சேர்ப்பதில் தோல்வி: ',
      'added_by': 'சேர்த்தவர்',
      'unknown': 'தெரியவில்லை',
      // Timeline
      'status_loading': 'ஏற்றுதல்',
      'status_unloading': 'இறக்குதல்',
      'status_waypoint': 'நிறுத்தம்',
      // Expense Types
      'etype_Fuel': 'எரிபொருள்',
      'etype_Toll': 'டோல்',
      'etype_Maintenance': 'பராமரிப்பு',
      'etype_Food': 'உணவு',
      'etype_Other': 'மற்றவை',
      'etype_Parking': 'பார்க்கிங்',
      'etype_Fuel Expense': 'எரிபொருள் செலவு',
      'etype_FASTag Expense': 'பாஸ்டேக் செலவு',
      // Active Job Page
      'vehicle_location_unknown': 'வாகன இருப்பிடம் தெரியவில்லை',
      'searching_pumps': 'இந்தியன் ஆயில் பம்புகளைத் தேடுகிறது...',
      'no_pumps_found': 'அருகில் இந்தியன் ஆயில் பம்புகள் எதுவும் இல்லை',
      'found_pumps': 'பம்புகள் கண்டுபிடிக்கப்பட்டன. வரைபடத்தில் மார்க்கரைத் தட்டவும்.',
      'tap_to_navigate': 'செல்ல தட்டவும்',
      'error_searching_fuel': 'எரிபொருளைத் தேடுவதில் பிழை: ',
      'routing_to': 'வழிகாட்டுதல்',
      'no_road_route_found': 'சாலை வழி கிடைக்கவில்லை.',
      'select_theme': 'தீம் தேர்ந்தெடுக்கவும்',
      'theme_system': 'கணினி இயல்புநிலை',
      'theme_light': 'லைட் மோட்',
      'theme_dark': 'டார்க் மோட்',
      'driver_role': 'ஓட்டுநர்',
      'job_label': 'பயணம்',
      'label_start': 'தொடக்கம்',
      'label_end': 'முடிவு',
      // Actions
      'action_loading': 'ஏற்றத் தொடங்கு',
      'action_unloading': 'இறக்கத் தொடங்கு',
      'action_loaded': 'ஏற்றி முடிந்தது',
      'action_unloaded': 'இறக்கி முடிந்தது',
      'loading_started': 'ஏற்றத் தொடங்கியது',
      'loading_completed': 'ஏற்றி முடிந்தது',
      'action_departed': 'புறப்படு',
      'action_reached': 'வந்தடைந்தது',
      'bill_image_opt': 'பில் படம் (விருப்பத்தேர்வு)',
      'bill_image_req': 'பில் படம் (கட்டாயம்)',
      'camera': 'கேமரா',
      'gallery': 'கேலரி',
      'bill_required_error': 'இந்த செலவிற்கு பில் படம் அவசியம்',
      'delete_expense': 'செலவை நீக்கு',
      'delete_expense_confirm': 'இந்தச் செலவை நிச்சயமாக நீக்க விரும்புகிறீர்களா?',
      'expense_deleted': 'செலவு வெற்றிகரமாக நீக்கப்பட்டது',
      'delete': 'நீக்கு',
      'cancel': 'ரத்து',
      // Driver Switch
      'switch_driver_title': 'ஓட்டுநரை மாற்றவா?',
      'switch_driver_content': 'ஓட்டுநர் பொறுப்பை மாற்ற விரும்புகிறீர்களா? இணை ஓட்டுநருக்கு OTP அனுப்பப்படும்.',
      'verify_codriver_title': 'இணை ஓட்டுநரை சரிபார்க்கவும்',
      'enter_otp_label': 'OTP உள்ளிடவும்',
      'verify_switch_btn': 'சரிபார்த்து மாற்றவும்',
      'driver_switched_success': 'ஓட்டுநர் வெற்றிகரமாக மாற்றப்பட்டார்!',
      'invalid_otp': 'தவறான OTP',
      'switch_verification_failed': 'சரிபார்ப்பு தோல்வியடைந்தது',
      'you_are_driving': 'நீங்கள் ஓட்டுகிறீர்கள்',
      'passenger_codriver': 'பயணி / இணை ஓட்டுநர்',
      'switch_btn': 'மாற்று',
      'send_otp': 'OTP அனுப்பு',
      'failed_request_switch': 'மாற்றக் கோரிக்கை தோல்வியடைந்தது',
      'take_over_title': 'பொறுப்பேற்கவா?',
      'take_over_content': 'ஓட்டுநர் பொறுப்பை ஏற்கவா? தற்போதைய ஓட்டுநருக்கு OTP அனுப்பப்படும்.',
      'take_over_btn': 'பொறுப்பேற்க',
      // Tyre Management
      'tyre_management_title': 'டயர் மேலாண்மை',
      'spare_rack': 'ஸ்பேர் டயர் ரேக்',
      'front': 'முன்பக்கம்',
      'move_swap': 'நகர்த்தவும் / மாற்றவும்',
      'swap_tyre_title': 'டயரை மாற்றவும்',
      'select_target_tyre': 'மாற்றுவதற்கு இலக்கு இடத்தை தேர்ந்தெடுக்கவும்',
      'brand': 'பிராண்ட்',
      'model': 'மாடல்',
      'serial': 'சீரியல்',
      'odometer_installed': 'ஓடோமீட்டர் நிறுவப்பட்டது',
      'total_run': 'மொத்த ஓட்டம்',
      'close': 'மூடு',
    },
  };

  // Dynamic translation cache
  final Map<String, String> _dynamicCache = {};
  final TranslationService _translationService = TranslationService();

  // Colloquial Dictionary for Logistics Terms (Manual Overrides for Better Quality)
  final Map<String, Map<String, String>> _colloquialDictionary = {
     // Unloading
     'unloading expense': {
        'hi': 'उतराई',
        'te': 'అన్లోడింగ్ ఖర్చులు', // Unloading Kharchulu
        'ta': 'இறக்கு செலவு', // Irakku Selavu (Requested)
        'kn': 'ಅನ್‌ಲೋಡಿಂಗ್ ವೆಚ್ಚ',
        'ml': 'ഇറക്ക് കൂലി' // Irakku kooli
     },
     'unloading charges': {
        'hi': 'उतराई शुल्क',
        'te': 'అన్లోడింగ్ ఛార్జీలు',
        'ta': 'இறக்கு கூலி', 
        'kn': 'ಅನ್‌ಲೋಡಿಂಗ್ ಶುಲ್ಕ',
        'ml': 'ഇറക്ക് കൂലി'
     },
     // Loading
     'loading expense': {
        'hi': 'लदाई',
        'te': 'లోడింగ్ ఖర్చులు',
        'ta': 'ஏற்று கூலி', // Yetru kooli
        'kn': 'ಲೋಡಿಂಗ್ ವೆಚ್ಚ',
        'ml': 'കയറ്റുകൂലി' // Kayattu kooli
     },
     // Official/Bribe (Common in logistics)
     'rto': {'hi': 'आरटीओ', 'ta': 'RTO', 'te': 'RTO', 'kn': 'RTO', 'ml': 'RTO'},
     'police': {'hi': 'पुलिस', 'ta': 'போலீஸ்', 'te': 'పోలీసు', 'kn': 'ಪೊಲೀಸ್', 'ml': 'പോലീസ്'},
     'border': {'hi': 'बॉर्डर', 'ta': 'எல்லை', 'te': 'సరిహద్దు', 'kn': 'ಗಡಿ', 'ml': 'അതിർത്തി'},
     'entry tax': {
        'hi': 'प्रवेश कर', 
        'ta': 'நுழைவு வரி', 
        'te': 'ప్రవేశ పన్ను',
        'kn': 'ಪ್ರವೇಶ ತೆರಿಗೆ',
        'ml': 'എൻട്രി ടാക്സ്'
     },
     'rto expense': {
        'hi': 'आरटीओ खर्चा',
        'te': 'RTO ఖర్చులు',
        'ta': 'RTO செலவு', 
        'kn': 'RTO ವೆಚ್ಚ',
        'ml': 'RTO ചെലവ്'
     },
     // Misc
     'tea': {'hi': 'चाय', 'ta': 'தேநீர்', 'te': 'టీ', 'kn': 'ಚಹಾ', 'ml': 'ചായ'},
     'courier charges': {
        'hi': 'कुरियर शुल्क',
        'ta': 'கூரியர் செலவு',
        'te': 'కొరియర్ ఛార్జీలు',
        'kn': 'ಕೊರಿಯರ್ ಶುಲ್ಕ',
        'ml': 'കൊറിയർ ചാർജ്'
     }
  };
  
  // Colloquial Suffixes for "Expense"
  final Map<String, String> _expenseSuffixes = {
    'hi': 'खर्चा',
    'te': 'ఖర్చులు',
    'ta': 'செலவு',
    'kn': 'ವೆಚ್ಚ',
    'ml': 'ചെലവ്',
  };

  String t(String key) {
    if (_localizedStrings[_locale.languageCode]!.containsKey(key)) {
      return _localizedStrings[_locale.languageCode]![key]!;
    }
    return key;
  }

  // Handle dynamic content (like new expense types)
  String translateDynamic(String text) {
    // 1. Check if we have a static mapping for this text (e.g. 'etype_Fuel' -> 'Fuel')
    // We try to construct a key 'etype_$text' just in case it matches a static key
    String normalizedText = text.trim();
    String staticKey = 'etype_$normalizedText';
    if (_localizedStrings[_locale.languageCode]!.containsKey(staticKey)) {
      return _localizedStrings[_locale.languageCode]![staticKey]!;
    }

    // 1b. Check Colloquial Dictionary (Robust overrides for logistics terms)
    final lowerText = normalizedText.toLowerCase();
    if (_colloquialDictionary.containsKey(lowerText)) {
       final dict = _colloquialDictionary[lowerText];
       if (dict != null && dict.containsKey(_locale.languageCode)) {
          return dict[_locale.languageCode]!;
       }
    }

    // 2. If English, return as is
    if (_locale.languageCode == 'en') return text;

    // 3. New Generic Suffix Logic (e.g. "XYZ Expense" -> "XYZ Selavu")
    if (lowerText.endsWith(' expense')) {
       final prefix = text.substring(0, text.length - 8).trim(); // Remove " Expense"
       if (prefix.isNotEmpty && _expenseSuffixes.containsKey(_locale.languageCode)) {
          final suffix = _expenseSuffixes[_locale.languageCode];
          // Recursively translate prefix (in case it is "Loading" etc)
          // But ensure we don't loop forever. Prefix "Loading" -> "Loading" dynamic -> "Yetru kooli"
          final translatedPrefix = translateDynamic(prefix); 
          
          // Construct the colloquial string
          // For Indian languages, usually "Prefix Suffix" (e.g. RTO Selavu)
          return '$translatedPrefix $suffix';
       }
    }

    // 4. Check dynamic cache

    final cacheKey = '${_locale.languageCode}_$text';
    if (_dynamicCache.containsKey(cacheKey)) {
      return _dynamicCache[cacheKey]!;
    }

    // 5. Trigger background translation and return original temporarily
    _translateInBackground(text, _locale.languageCode);
    
    return text;
  }

  Future<void> _translateInBackground(String text, String targetLang) async {
    final cacheKey = '${targetLang}_$text';
    // Use a temporary lock mechanism or check if already translating could be added, 
    // but for simplicity we just allow redundant calls (ML Kit handles them fast).
    
    final translated = await _translationService.translate(text, targetLang);
    if (translated != text) {
      _dynamicCache[cacheKey] = translated;
      notifyListeners(); // Refresh UI once translation is ready
    }
  }
}
